// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Schulprojekt.Data;

#nullable disable

namespace Schulprojekt.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260319193645_Add_GamePlaceName_And_Description")]
    partial class Add_GamePlaceName_And_Description
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Schulprojekt.Data.Character", b =>
                {
                    b.Property<int>("CharacterID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Backstory")
                        .HasColumnType("longtext");

                    b.Property<int>("GettingByCompletingTheme")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("NormalEndText")
                        .HasColumnType("longtext");

                    b.Property<string>("ProfiEndText")
                        .HasColumnType("longtext");

                    b.Property<string>("TopEndText")
                        .HasColumnType("longtext");

                    b.HasKey("CharacterID");

                    b.ToTable("Character");
                });

            modelBuilder.Entity("Schulprojekt.Data.GapField", b =>
                {
                    b.Property<int>("GapId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("CaseSensitive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("CorrectText")
                        .HasColumnType("longtext");

                    b.Property<int>("GapIndex")
                        .HasColumnType("int");

                    b.Property<string>("InputType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.HasKey("GapId");

                    b.HasIndex("QuestionId", "GapIndex")
                        .IsUnique();

                    b.ToTable("GapFields");
                });

            modelBuilder.Entity("Schulprojekt.Data.GapOption", b =>
                {
                    b.Property<int>("GapOptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("GapId")
                        .HasColumnType("int");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("OptionOrder")
                        .HasColumnType("int");

                    b.Property<string>("OptionText")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("GapOptionId");

                    b.HasIndex("GapId", "OptionOrder")
                        .IsUnique();

                    b.ToTable("GapOptions");
                });

            modelBuilder.Entity("Schulprojekt.Data.McAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("OptionOrder")
                        .HasColumnType("int");

                    b.Property<string>("OptionText")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("McAnswers");
                });

            modelBuilder.Entity("Schulprojekt.Data.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("AllowsMultiple")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("EndText")
                        .HasColumnType("longtext");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext");

                    b.Property<int>("QuestionSetId")
                        .HasColumnType("int");

                    b.Property<string>("QuestionType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("StartText")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("QuestionSetId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("Schulprojekt.Data.QuestionSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<int>("ThemaId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.HasIndex("ThemaId");

                    b.ToTable("QuestionSets");
                });

            modelBuilder.Entity("Schulprojekt.Data.QuestionSetProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("CharacterId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsPassed")
                        .HasColumnType("tinyint(1)");

                    b.Property<double?>("MaxPoints")
                        .HasColumnType("double");

                    b.Property<int?>("Points")
                        .HasColumnType("int");

                    b.Property<int>("QuestionSetId")
                        .HasColumnType("int");

                    b.Property<int>("SpielerId")
                        .HasColumnType("int");

                    b.Property<int>("ThemaId")
                        .HasColumnType("int");

                    b.Property<string>("Topic")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("QuestionSetProgresses");
                });

            modelBuilder.Entity("Schulprojekt.Data.Spieler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Schulprojekt.Data.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("Schulprojekt.Data.Thema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("GamePlaceDescription")
                        .HasColumnType("longtext");

                    b.Property<string>("GamePlaceName")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Themen");
                });

            modelBuilder.Entity("Schulprojekt.Data.GapField", b =>
                {
                    b.HasOne("Schulprojekt.Data.Question", "Question")
                        .WithMany("GapFields")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Schulprojekt.Data.GapOption", b =>
                {
                    b.HasOne("Schulprojekt.Data.GapField", "GapField")
                        .WithMany("GapOptions")
                        .HasForeignKey("GapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GapField");
                });

            modelBuilder.Entity("Schulprojekt.Data.McAnswer", b =>
                {
                    b.HasOne("Schulprojekt.Data.Question", "Question")
                        .WithMany("McAnswers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Schulprojekt.Data.Question", b =>
                {
                    b.HasOne("Schulprojekt.Data.QuestionSet", "QuestionSet")
                        .WithMany("Questions")
                        .HasForeignKey("QuestionSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuestionSet");
                });

            modelBuilder.Entity("Schulprojekt.Data.QuestionSet", b =>
                {
                    b.HasOne("Schulprojekt.Data.Team", "Team")
                        .WithMany("QuestionSets")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Schulprojekt.Data.Thema", "Thema")
                        .WithMany("QuestionSets")
                        .HasForeignKey("ThemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");

                    b.Navigation("Thema");
                });

            modelBuilder.Entity("Schulprojekt.Data.QuestionSetProgress", b =>
                {
                    b.HasOne("Schulprojekt.Data.Character", "Character")
                        .WithMany("QuestionSetProgresses")
                        .HasForeignKey("CharacterId");

                    b.Navigation("Character");
                });

            modelBuilder.Entity("Schulprojekt.Data.Character", b =>
                {
                    b.Navigation("QuestionSetProgresses");
                });

            modelBuilder.Entity("Schulprojekt.Data.GapField", b =>
                {
                    b.Navigation("GapOptions");
                });

            modelBuilder.Entity("Schulprojekt.Data.Question", b =>
                {
                    b.Navigation("GapFields");

                    b.Navigation("McAnswers");
                });

            modelBuilder.Entity("Schulprojekt.Data.QuestionSet", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("Schulprojekt.Data.Team", b =>
                {
                    b.Navigation("QuestionSets");
                });

            modelBuilder.Entity("Schulprojekt.Data.Thema", b =>
                {
                    b.Navigation("QuestionSets");
                });
#pragma warning restore 612, 618
        }
    }
}
