using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Schulprojekt.Migrations
{
    /// <inheritdoc />
    public partial class SeederQuestions : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Optional: delete existing rows with these IDs to avoid duplicates
            migrationBuilder.Sql("DELETE FROM `questions` WHERE `Id` BETWEEN 1 AND 2;");

            migrationBuilder.Sql(@"
            INSERT INTO `questions` 
            (`Id`, `StartText`, `ImageUrl`, `EndText`, `AllowsMultiple`, `QuestionType`, `QuestionSetId`)
            VALUES
            (1, 'Welche beiden Regelungen finden Sie in einem Manteltarifvertrag?', NULL, NULL, 1, 'MC', 1),
            (2, 'In der MaHaG KG steht die Wahl des Betriebsrates an. Welche 3 Personen sind wahlberechtigt ?', NULL, NULL, 1, 'MC', 1),
            
            
(3, 'Mit Ihren Auszubildenen sprechen Sie über die anstehenden Betriebswahlen. Welche beiden Aussagen sind richtig ?', NULL, NULL, 1, 'MC', 1),
(4, 'Welche beiden Sachverhalte sind im Allgemeinen Gleichbehandlungsgesetz (AGG) geregelt?', NULL, NULL, 1, 'MC', 1),
(5, 'Die MaHaG KG plant, einen Fachinformatiker Anwendungsentwicklung (m/w/d) einzustellen. Nachdem Sie das Anforderungsprofil entworfen haben, weist Ihre Rechtsabteilung Sie darauf hin, dass eine Formulierung gegen das Allgemeine Gleichbehandlungsgesetz (AGG) verstößt. Was dürfen Sie nicht in eine Stellenbeschreibung nach dem AGG schreiben?', NULL, NULL, 0, 'MC', 1),
(6, 'Bei der Gestaltung der Ausbildungsverträge für volljährige und jugendliche Auszubildende müssen Sie darauf achten, dass gesetzliche Bestimmungen eingehalten werden. In welchen beiden Gesetzen schauen Sie nach, wenn Sie Inhalte eines Ausbildungsvertrages prüfen möchten?', NULL, NULL, 1, 'MC', 1),
(7, 'Welche zwei Bestimmungen finden Sie im Berufsbildungsgesetz?', NULL, NULL, 1, 'MC', 1),
(8, 'Jens Rievers hat am 16.07.2025 seine Ausbildung mit dem Bestehen der letzten Prüfung erfolgreich beendet. Weil sein Ausbildungsvertrag als Vertragsende den 31.07.2025 vorsieht, ist er der Meinung, dass er bis zu diesem Zeitpunkt arbeiten muss. Welche Rechtsfolge tritt ein, wenn er ab dem 17.07.2025 in der bisherigen Abteilung weiterarbeitet?', NULL, NULL, 0, 'MC', 1),
(9, 'Bei der MaHaG KG stehen Wahlen zur Jugend- und Auszubildendenvertretung an. Katja Sommer (Vertriebsmitarbeiterin, 24 Jahre alt), die bereits im Betriebsrat ist und umfangreiche Erfahrungen dort gesammelt hat, will nun auch für dieses Amt kandidieren. Prüfen Sie, ob das möglich ist. Beachten Sie hierzu den folgenden Gesetzestext:', NULL, NULL, 0, 'MC', 1),
(10, 'Bevor Sie die Ausbildungsverträge den Auszubildenden schicken, überprüfen Sie diese. Ein Ausbildungsvertrag weist einen Fehler auf, der gegen das Berufsbildungsgesetz verstößt. Um welchen Fehler handelt es sich hier?', NULL, NULL, 0, 'MC', 1),
(11, 'Unternehmen können in der Form einer Personengesellschaft oder als juristische Person geführt werden. Auf welchen der folgenden Begriffe trifft die Bezeichnung „Juristische Person des privaten Rechts“ zu?', NULL, NULL, 0, 'MC', 1),
(12, 'Zu den Kunden der MaHaG KG zählen neben den Personengesellschaften auch juristische Personen des privaten und des öffentlichen Rechts. Bei welchen beiden Kunden der MaHaG KG handelt es sich um juristische Personen des öffentlichen Rechts?', NULL, NULL, 1, 'MC', 1),
(13, 'Um ihr Kapital sinnvoll einzusetzen und zu verwerten, handelt die MaHaG KG zunächst einmal nach dem ökonomischen Prinzip.', NULL, NULL, 1, 'MC', 1),
(14, 'Prüfen Sie, welche der folgenden Maßnahmen der MaHaG KG keine ökologische Zielsetzung beinhaltet.', NULL, NULL, 0, 'MC', 1),
(15, 'Bei der Verfolgung ökonomischer Ziele berücksichtigt die MaHaG KG auch zunehmend Aspekte des Umweltschutzes. Prüfen Sie, wo Zielharmonie herrscht, also ökonomische und ökologische Aspekte im Einklang sind.', NULL, NULL, 1, 'MC', 1),
(16, 'Im Rahmen der von den Unternehmen praktizierten Kommunikationspolitik weisen Firmen verstärkt auf verantwortungsbewusstes und nachhaltiges Wirtschaften hin. Bei welcher Maßnahme wirtschaftet die MaHaG KG ökologisch nachhaltig und kann werbewirksam darauf hinweisen?', NULL, NULL, 0, 'MC', 1),
(17, 'Für ihre mittel- und langfristige Planung benötigt die MaHaG KG Informationen, in welcher Konjunkturphase sich aktuell die wirtschaftliche Entwicklung befindet. Welche Merkmale kennzeichnen den Abschwung?', NULL, NULL, 0, 'MC', 1),
(18, 'Wie sollte die Mannheimer Haushaltsgeräte KG im Falle eines beginnenden Abschwungs agieren?\n(2 Antworten)', NULL, NULL, 1, 'MC', 1),
(19, 'Auf einem Markt treffen Angebot und Nachfrage aufeinander.\nBei einem bestimmten Preis sind angebotene Menge und nachgefragte Menge genau gleich groß.', NULL, NULL, 0, 'MC', 1),
(20, 'Prüfen Sie, welche der nachstehenden Aussagen über den einfachen Wirtschaftskreislauf richtig ist.', NULL, NULL, 0, 'MC', 1),
(21, 'Die verschiedenen Konjunkturphasen veranlassen auch die Mannheimer Haushaltsgeräte KG, ihr wirtschaftliches Verhalten danach auszurichten. Prüfen Sie, in welcher Konjunkturphase sich die MaHaG KG ökonomisch sinnvoll verhält.', NULL, NULL, 0, 'MC', 1),
(22, 'Ein Auszubildender der MaHaG KG stürzt im Hauptlagerhaus beim Einsortieren von Waren von der Leiter und bricht sich ein Bein. Wem muss die entsprechende Unfallmeldung zugeleitet werden?', NULL, NULL, 0, 'MC', 1),
(23, 'Marga Schlöter, angehende Kauffrau für Büromanagement, informiert sich bei Ihnen über die Regelungen zur Arbeitsunfähigkeit. Welche zwei Aussagen hierzu sind richtig?', NULL, NULL, 1, 'MC', 1),
(24, 'Gerda Kalinov ist Prokuristin der Mannheimer Haushaltsgeräte KG und im Handelsregister eingetragen.', NULL, NULL, 1, 'MC', 1),
(25, 'Für welche Unternehmensform wird Claudia Both sich unter diesen Voraussetzungen entscheiden?', NULL, NULL, 0, 'MC', 1),
(26, 'Für ein Darlehen zur Existenzgründung verlangt die Bank von Claudia Both einen Businessplan. Wozu dient dieser?', NULL, NULL, 0, 'MC', 1),
(27, 'Carlos Ortega, 17 Jahre alt, beginnt am 01.08.2025 seine Berufsausbildung als Fachinformatiker bei der MaHaG KG. Der Auszubildende vollendet am 15.01.2026 das 18. Lebensjahr.', NULL, NULL, 0, 'MC', 1),
(28, 'Der Auszubildende Igor Czerwinski muss im Rahmen seiner Ausbildung immer wieder Tätigkeiten verrichten, die nach dem Berufsbild ausbildungsfremd und im betrieblichen Ausbildungsplan nicht vorgesehen sind.', NULL, NULL, 0, 'MC', 1),
(29, 'Fatima Kuslu, 17 Jahre alt, hat am 1. September ihre Berufsausbildung als Fachinformatikerin bei der MaHaG KG begonnen. Welche Vorschrift des Jugendarbeitsschutzgesetzes gilt für sie?', NULL, NULL, 0, 'MC', 1),
(30, 'Arbeitnehmer erhalten im Krankheitsfall weiterhin ihre Vergütung, obwohl sie ihre Arbeitsleistung nicht erbringen können. Gilt das auch gleichermaßen für Auszubildende?', NULL, NULL, 0, 'MC', 1),
(31, 'In der Mannheimer Haushaltsgeräte KG wurde dem Auszubildenden Mario Klug fristlos gekündigt, weil er beim Aufbrechen eines Spindes ertappt wurde. Der Betriebsrat wurde nach der fristlosen Kündigung informiert und stimmte dieser nachträglich bedenkenlos zu.', NULL, NULL, 0, 'MC', 1),
(32, 'In den Arbeitsverträgen der MaHaG KG ist wie auch in den Ausbildungsverträgen immer eine Probezeit vereinbart. Wodurch unterscheidet sich die Probezeit in einem Ausbildungsvertrag von der in einem Arbeitsvertrag? (Zwei Antworten)', NULL, NULL, 0, 'MC', 1),
(33, 'Ein Ausbildungsvertrag ist ein befristeter Vertrag, der automatisch durch Zeitablauf endet. Wann ist die Kündigung eines solchen Ausbildungsvertrages dennoch möglich? (Zwei Antworten)', NULL, NULL, 1, 'MC', 1),
(34, 'Der Betriebsrat hat abgestufte Rechte. In welchem Fall hat der Betriebsrat nur ein Informationsrecht?', NULL, NULL, 0, 'MC', 1),
(35, 'Jan Riekers möchte ein Praktikum im Ausland zur Verbesserung seiner Sprachkenntnisse machen. Sie weisen ihn auf den Europass hin.', NULL, NULL, 0, 'MC', 1),
(36, 'Am 28.10.20XX kündigt Mina Stiller (38 Jahre, seit 11 Jahren im Unternehmen) fristgerecht zum nächstmöglichen Termin.\nNennen Sie das Datum, an dem Frau Stiller frühestens eine neue Stelle antreten kann.', NULL, NULL, 0, 'MC', 1),
(37, 'In der MaHaG KG stehen Betriebsratswahlen an. Das Unternehmen hat 134 Beschäftigte (volljährig) und 16 Azubis (12 davon volljährig). Darüber hinaus sind 3 Zeitarbeitnehmer seit 4 Monaten im Betrieb damit beschäftigt, für die IT-Sicherheit zu sorgen.', NULL, NULL, 0, 'MC', 1),
(38, 'Zur Produktion ihrer Haushaltsgeräte benötigt die Mannheimer Haushaltsgeräte KG Ressourcen und kombiniert Produktionsfaktoren miteinander.', NULL, NULL, 1, 'MC', 1),
(39, 'Abfallvermeidung bedeutet neben der Entlastung der Umwelt auch Kosteneinsparungen bei der Mannheimer Haushaltsgeräte KG, also eine Zielharmonie zwischen Ökonomie und Ökologie. Welche der folgenden Maßnahmen gehört zur Abfallvermeidung?', NULL, NULL, 0, 'MC', 1),
(40, 'Immer wieder fragen Kunden nach einer weiteren Entwicklung vernetzter Haushaltsgeräte.\nBundesweit gibt es neben der MaHaG KG nur noch drei weitere Hersteller dieser zukunftsweisenden Technologie.', NULL, NULL, 0, 'MC', 1),
(41, 'Die Mannheimer Haushaltsgeräte KG steht bei ihrem Angebot an kleinen Haushaltsgeräten und Zubehör mit einer Vielzahl von Mitbewerbern mit kleinen Angebotsmengen am Markt in einem Wettbewerbsprozess. Auf der Nachfrageseite gibt es eine Vielzahl von Haushalten und Unternehmen mit ihren Werkskantinen.', NULL, NULL, 0, 'MC', 1),
(42, 'Die Wirtschaftsordnung der Bundesrepublik Deutschland bezeichnet man als „Soziale Marktwirtschaft“.\nBesonderes Merkmal dieser Wirtschaftsordnung ist ein funktionierender Markt. Welche Eigenschaften und Entwicklungen zeichnen diesen Markt aus?', NULL, NULL, 0, 'MC', 1),
(43, 'Ohne staatliche oder anderweitige Eingriffe in das Marktgeschehen bildet sich am Markt zwischen Angebot und Nachfrage der sog. „Gleichgewichtspreis“. Welche Funktion erfüllt dieser?', NULL, NULL, 0, 'MC', 1),
(44, 'Prüfen Sie, welche der nachstehenden Aussagen über den einfachen Wirtschaftskreislauf richtig ist.', NULL, NULL, 0, 'MC', 1),
(45, 'Die MaHaG KG ist in den letzten Jahren stark gewachsen. Die Geschäftsleitung denkt über eine Reorganisation des Unternehmens nach. Als Mitarbeiter/-in der Stabsstelle „Betriebswirtschaftliche Analyse und Planung“ sollen Sie die Aufbauorganisation Ihres Unternehmens überprüfen. Sie schauen sich auch die Organisationsstrukturen kooperierender Unternehmen an. Die MaHaG verwendet das Stabliniensystem.', NULL, NULL, 0, 'MC', 1),
(46, 'Clara Bürscheid (21 Jahre), Mitarbeiterin im Einkauf, möchte sich bei den anstehenden Wahlen der Jugend- und Auszubildendenvertretung als Kandidatin aufstellen lassen.', NULL, NULL, 0, 'MC', 1),
(47, 'Nachhaltiges Wirtschaften zeichnet sich insbesondere dadurch aus, dass Ressourcen wiederverwendet werden. Bei welcher der folgenden Maßnahmen handelt die Mannheimer Haushaltsgeräte KG nachhaltig?', NULL, NULL, 0, 'MC', 1),
(48, 'Aus gelieferten Edelstahlblechen fertigt die Mannheimer Haushaltsgeräte KG Edelstahlgehäuse für Waschmaschinen und Trockner. Beim Zuschneiden der Bleche fallen Reste an, die nicht unmittelbar verwendet werden können. Das Unternehmen liefert daher diese Reste an ein Edelstahlwerk, das diese einschmilzt und daraus neue Edelstahlbleche gewinnt. Welche Bezeichnung gibt es für diese Form der Rohstoffeinsparung?', NULL, NULL, 0, 'MC', 1),
(49, 'Die Tarifvertragsparteien – Arbeitgeberverbände und Gewerkschaften – können die Arbeits- und Wirtschaftsbedingungen ohne staatliche Einmischung frei gestalten.', NULL, NULL, 0, 'MC', 1),
(50, 'Was ist das Kernmerkmal des Minimalprinzips?', NULL, NULL, 0, 'MC', 2),
(51, 'Welches Szenario beschreibt ein Oligopol?', NULL, NULL, 0, 'MC', 2),
(52, 'Warum sinkt die Kaufkraft bei Inflation?', NULL, NULL, 0, 'MC', 2),
(53, 'Was wird im Bruttoinlandsprodukt (BIP) NICHT berücksichtigt?', NULL, NULL, 0, 'MC', 2),
(54, 'Wie reagiert der Gleichgewichtspreis, wenn das Angebot sinkt, die Nachfrage aber gleich bleibt?', NULL, NULL, 0, 'MC', 2),
(55, 'Was verstehen Ökonomen unter Opportunitätskosten?', NULL, NULL, 0, 'MC', 2),
(56, 'Wie unterscheidet sich die AG von der GmbH bei der Kapitalbeschaffung?', NULL, NULL, 0, 'MC', 2),
(57, 'Welcher Zielkonflikt besteht oft in Unternehmen?', NULL, NULL, 0, 'MC', 2),
(58, 'Wann ist Leasing für ein Unternehmen wirtschaftlich oft sinnvoll?', NULL, NULL, 0, 'MC', 2),
(59, 'Wie lautet die Formel zur Berechnung des Break-Even-Points (in Stück)?', NULL, NULL, 0, 'MC', 2),
(60, 'Welches Kriterium ist für ein Projekt essenziell?', NULL, NULL, 0, 'MC', 2),
(61, 'Wie beeinflussen sich die Faktoren im \""Magischen Dreieck\""?', NULL, NULL, 0, 'MC', 2),
(62, 'Warum ist der Projektstrukturplan so wichtig?', NULL, NULL, 0, 'MC', 2),
(63, 'Was passiert, wenn sich eine Aufgabe auf dem \""Kritischen Pfad\"" verzögert?', NULL, NULL, 0, 'MC', 2),
(64, 'Wofür steht das \""R\"" in der SMART-Methode?', NULL, NULL, 0, 'MC', 2),
(65, 'Warum ist der Abnahmebericht rechtlich wichtig?', NULL, NULL, 0, 'MC', 2),
(66, 'Was ist das Problem in einer Matrix-Organisation?', NULL, NULL, 0, 'MC', 2),
(67, 'Was ist der \""Freie Puffer\""?', NULL, NULL, 0, 'MC', 2),
(68, 'Welche Information liefert ein Gantt-Diagramm?', NULL, NULL, 0, 'MC', 2),
(69, 'Was ist die Hauptaufgabe des Scrum Masters?', NULL, NULL, 0, 'MC', 2),
(70, 'Welches UML-Diagramm wird hauptsächlich verwendet, um die statische Struktur eines Systems darzustellen?', NULL, NULL, 0, 'TF', 3),
(71, 'Welche Beziehung wird im UML-Klassendiagramm durch eine durchgezogene Linie mit einer ausgefüllten Raute dargestellt?', NULL, NULL, 0, 'TF', 3),
(72, 'Welche Art von Beziehung beschreibt eine Vererbung zwischen zwei Klassen?', NULL, NULL, 0, 'TF', 3),
(73, 'Welche Elemente können in einem UML-Klassendiagramm vorkommen?', NULL, NULL, 1, 'MC', 3),
(74, 'Welche UML-Diagramme zählen zu den Strukturdiagrammen?', NULL, NULL, 1, 'MC', 3),
(75, 'Welche Beziehungen können im Klassendiagramm dargestellt werden?', NULL, NULL, 1, 'MC', 3),
(76, 'Ein UML-Klassendiagramm beschreibt die _____ Struktur eines Systems und zeigt unter anderem Klassen, Attribute und _____.', '', '.', 0, 'GAP', 3),
(77, 'Die Komposition wird im UML‑Klassendiagramm durch eine _____ Raute dargestellt und beschreibt eine besonders starke _____-Teil-Beziehung.', '', '.', 0, 'GAP', 3),
(78, 'In einem Klassendiagramm steht das Minuszeichen (–) für _____ Sichtbarkeit, während das Pluszeichen (+) für _____ Sichtbarkeit steht.', '', '.', 0, 'GAP', 3),
(79, 'Eine Aggregation ist stärker als eine Komposition.', NULL, NULL, 0, 'TF', 3),
(80, 'Eine synchrone Nachricht blockiert den Sender, bis eine Antwort erfolgt.', NULL, NULL, 0, 'TF', 4),
(81, 'Ein opt-Fragment ist ein Spezialfall eines alt‑Fragments.', NULL, NULL, 0, 'TF', 4),
(82, 'Eine Aktivierung zeigt an, dass ein Objekt gerade eine Operation ausführt.', NULL, NULL, 0, 'TF', 4),
(83, 'Welches UML-Diagramm zeigt die Interaktion zwischen Objekten in zeitlicher Reihenfolge?', NULL, NULL, 0, 'TF', 4),
(84, 'Welche Aussage über Sequenzdiagramme trifft zu?', NULL, NULL, 0, 'TF', 4),
(85, 'Welche Aussage über kombinierte Fragmente ist korrekt?', NULL, NULL, 0, 'TF', 4),
(86, 'Welche Aussagen über Lebenslinien sind korrekt?', NULL, NULL, 1, 'MC', 4),
(87, 'Welche Elemente können in einem Sequenzdiagramm vorkommen?', NULL, NULL, 1, 'MC', 4),
(88, 'Eine synchrone Nachricht blockiert den Sender, bis eine _____ erfolgt, während eine asynchrone Nachricht _____ ausgeführt wird.', '', '.', 0, 'GAP', 4),
(89, 'Ein kombiniertes Fragment mit dem Operator _____ beschreibt alternative Abläufe, während der Operator _____Wiederholungen modelliert.', '', '.', 0, 'GAP', 4),
(90, 'Ein Aktivitätsdiagramm kann sowohl Kontroll‑ als auch Objektflüsse enthalten.', NULL, NULL, 0, 'TF', 5),
(91, 'Ein Fork-Knoten darf nur zwei ausgehende Kanten besitzen.', NULL, NULL, 0, 'TF', 5),
(92, 'Swimlanes dienen der Darstellung von Verantwortlichkeiten.', NULL, NULL, 0, 'TF', 5),
(93, 'Wofür wird ein Aktivitätsdiagramm hauptsächlich verwendet?', NULL, NULL, 0, 'TF', 5),
(94, 'Welche Aussage über Objektknoten ist korrekt?', NULL, NULL, 0, 'TF', 5),
(95, 'Welches Diagramm eignet sich am besten, um den Ablauf eines Prozesses mit Verzweigungen und Schleifen darzustellen?', NULL, NULL, 0, 'TF', 5),
(96, 'Welche Elemente können in einem Aktivitätsdiagramm vorkommen?', NULL, NULL, 1, 'MC', 5),
(97, 'Welche Aussagen über Partitionen (Swimlanes) sind korrekt?', NULL, NULL, 1, 'MC', 5),
(98, 'Ein Fork-Knoten teilt einen Ablauf in mehrere _____ Kontrollflüsse auf, während ein Join-Knoten diese wieder zu einem _____ Kontrollfluss zusammenführt.', '', '.', 0, 'GAP', 5),
(99, 'Ein Entscheidungsknoten teilt den Ablauf basierend auf _____ auf, während ein Zusammenführungsknoten mehrere _____ wieder zusammenführt.', '', '.', 0, 'GAP', 5),
(100, 'Ein Übergang darf keine Aktion besitzen, wenn er aus einem Endzustand kommt.', NULL, NULL, 0, 'TF', 6),
(101, 'Ein Übergang kann mehrere Ereignisse gleichzeitig als Trigger besitzen.', NULL, NULL, 0, 'TF', 6),
(102, 'Ein Endzustand darf keine ausgehenden Übergänge besitzen.', NULL, NULL, 0, 'TF', 6),
(103, 'Welche Aussage über Zustandsdiagramme ist korrekt?', NULL, NULL, 0, 'TF', 6),
(104, 'Welche Aussage über Subzustände ist korrekt?', NULL, NULL, 0, 'TF', 6),
(105, 'Welche Darstellung gehört typischerweise zu einem Zustandsdiagramm?', NULL, NULL, 0, 'TF', 6),
(106, 'Welche Symbole können in einem Zustandsdiagramm vorkommen?', NULL, NULL, 1, 'MC', 6),
(107, 'Welche Aussagen über Übergänge sind korrekt?', NULL, NULL, 1, 'MC', 6),
(108, 'Ein Zustand kann interne Aktivitäten besitzen, die als _____, _____ oder _____ bezeichnet werden.', '', '.', 0, 'GAP', 6),
(109, 'Ein Zustandsdiagramm beschreibt, wie ein Objekt auf _____ reagiert und dabei von einem Zustand in den _____ übergeht.', '', '.', 0, 'GAP', 6),
(110, 'Bei einer Offenen Handelsgesellschaft (OHG) ist die Haftung auf das Gesellschaftsvermögen beschränkt.', NULL, NULL, 0, 'TF', 7),
(111, 'Die Marktform, bei der wenigen Anbietern sehr viele Nachfrager gegenüberstehen, nennt man Angebotsoligopol.', NULL, NULL, 0, 'TF', 7),
(112, 'In einer SWOT-Analyse beziehen sich die \""Stärken\"" (Strengths) auf externe Faktoren, die für ein Unternehmen vorteilhaft sein könnten.', NULL, NULL, 0, 'TF', 7),
(113, 'Das primäre Ziel der Nutzwertanalyse (Scoring-Modell) bei der Entscheidungsfindung ist es, qualitative, schwer messbare Kriterien durch Gewichtung und Punktevergabe vergleichbar zu machen.', NULL, NULL, 0, 'TF', 7),
(114, 'Unter dem Begriff \""Green IT\"" versteht man primär die Gestaltung der Informations- und Kommunikationstechnik über den gesamten Lebenszyklus hinweg unter ökologischen Gesichtspunkten.', NULL, NULL, 0, 'TF', 7),
(115, '\""Corporate Identity\"" (CI) bezeichnet eine gesetzlich vorgeschriebene Identifikationsnummer für Unternehmen.', NULL, NULL, 0, 'TF', 7),
(116, 'Erhält ein Kunde eine Rechnung mit dem Vermerk \""Zahlbar bis zum 15. Mai\"" und zahlt nicht, gerät er mit Ablauf des 15. Mai automatisch in Verzug, ohne dass eine Mahnung erforderlich ist.', NULL, NULL, 0, 'TF', 7),
(117, 'Das wesentliche Unterscheidungsmerkmal ist, dass die Hypothek vom Bestand der zu sichernden Forderung abhängig ist (akzessorisch), die Grundschuld hingegen davon unabhängig ist (abstrakt).', NULL, NULL, 0, 'TF', 7),
(118, 'Ein kennzeichnendes Merkmal für die Globalisierung der Weltwirtschaft ist die Konzentration der Produktion ausschließlich auf den nationalen Binnenmarkt.', NULL, NULL, 0, 'TF', 7),
(119, 'Damit man modellhaft von einem \""vollkommenen Markt\"" spricht, müssen die gehandelten Güter völlig gleichartig (homogen) sein und es muss vollständige Markttransparenz herrschen.', NULL, NULL, 0, 'TF', 7),
(120, 'In der Wirtschaftstheorie handelt der sogenannte \""Homo oeconomicus\"" rational und strebt nach maximalem Nutzen (Nutzenmaximierung).', NULL, NULL, 0, 'TF', 7),
(121, 'Herr Müller ist seit sechs Jahren in der XYZ GmbH beschäftigt (kein Tarifvertrag). Der Arbeitgeber möchte ihm ordentlich kündigen. Welche gesetzliche Kündigungsfrist muss beachtet werden?', NULL, NULL, 0, 'MC', 7),
(122, 'Ab welcher Anzahl von ständigen wahlberechtigten Arbeitnehmern können in einem Betrieb Betriebsräte gewählt werden?', NULL, NULL, 0, 'MC', 7),
(123, 'Ein IT-Systemhaus kauft Server-Hardware zum Listeneinkaufspreis von 10.000 €. Der Lieferant gewährt 10 % Rabatt. Bei Zahlung innerhalb von 10 Tagen können zudem 2 % Skonto abgezogen werden. Wie hoch ist der Bareinkaufspreis?', NULL, NULL, 0, 'MC', 7),
(124, 'Eine neue Maschine kostet 120.000 €. Die jährlichen Rückflüsse (Gewinn + Abschreibungen) betragen konstant 30.000 €. Wie hoch ist die statische Amortisationszeit?', NULL, NULL, 0, 'MC', 7),
(125, 'Welche der folgenden Personengruppen genießen in Deutschland einen besonderen Kündigungsschutz?', NULL, NULL, 1, 'MC', 7),
(126, 'Welche Phasen existieren im Produktlebenszyklus?', NULL, NULL, 1, 'MC', 7),
(127, 'Welche der folgenden Aussagen zu Kapitalgesellschaften (GmbH, AG) sind wahr?', NULL, NULL, 1, 'MC', 7),
(128, 'Welche der folgenden Berufe oder Branchen werden dem tertiären Wirtschaftssektor (Dienstleistungssektor) zugeordnet?', NULL, NULL, 1, 'MC', 7),
(129, 'Welche Merkmale treffen typischerweise auf die Fremdfinanzierung zu?', NULL, NULL, 1, 'MC', 7),
(130, 'Welche der folgenden Positionen werden in der Bezugskalkulation als Bezugskosten (Hinzurechnungen) gewertet, die den Preis erhöhen?', NULL, NULL, 1, 'MC', 7),
(131, 'Welche Maßnahme gehört eindeutig zum operativen Marketing (und nicht zum strategischen)?', NULL, NULL, 1, 'MC', 7),
(132, 'Welche der folgenden Maßnahmen tragen konkret zur Umsetzung von Green IT in einem Unternehmen bei?', NULL, NULL, 1, 'MC', 7),
(133, 'Welche der folgenden Aufgaben gehören typischerweise zu den Kernfunktionen des operativen Controllings?', NULL, NULL, 1, 'MC', 7),
(134, 'Welche der folgenden Auswirkungen werden typischerweise mit der Globalisierung verbunden?', NULL, NULL, 1, 'MC', 7),
(135, 'Welche Aussagen zum Themenkomplex Bedürfnis, Bedarf und Nachfrage sind korrekt?', NULL, NULL, 1, 'MC', 7),
(136, 'Wodurch zeichnen sich \""Wirtschaftsgüter\"" (im Gegensatz zu freien Gütern) aus?', NULL, NULL, 1, 'MC', 7),
(137, 'Welche Rechte stehen einem Gläubiger (z. B. einem Lieferanten) grundsätzlich zu, wenn sich der Schuldner im Zahlungsverzug befindet?', NULL, NULL, 1, 'MC', 7),
(138, 'Welche der folgenden Kreditsicherheiten zählen zu den sogenannten Realsicherheiten (Sachsicherheiten)?', NULL, NULL, 1, 'MC', 7),
(139, 'Die Beendigung von Arbeitsverhältnissen durch Kündigung oder Auflösungsvertrag bedarf zu ihrer Wirksamkeit der _____ die elektronische Form ist _____.', '', '', 0, 'GAP', 7),
(140, 'Der Stückdeckungsbeitrag ist die Differenz zwischen dem Nettoverkaufserlös und den _____ Kosten eines Produkts. Er dient in erster Linie dazu, die im Unternehmen anfallenden _____ Kosten zu decken.', '', '', 0, 'GAP', 7),
(141, 'Das _____ beschreibt die theoretisch maximal mögliche Absatzmenge eines Produktes in einem bestimmten Zeitraum, während das _____ den tatsächlichen Gesamtabsatz aller Anbieter auf diesem Markt darstellt.', '', '', 0, 'GAP', 7),
(142, 'Der primäre Sektor befasst sich mit der Gewinnung von _____ , wie beispielsweise in der Forstwirtschaft oder Fischerei. Im Gegensatz dazu umfasst der sekundäre Sektor die _____ von Gütern, wie etwa im Handwerk oder der Industrie.', '', '', 0, 'GAP', 7),
(143, 'Beim Factoring verkauft ein Unternehmen seine offenen _____ an ein Finanzierungsinstitut (den Factor), um sofortige Liquidität zu erhalten und das Ausfallrisiko zu übertragen.', '', '', 0, 'GAP', 7),
(144, 'Der finale Preis, der sich ergibt, nachdem vom Listeneinkaufspreis alle Preisnachlässe (Rabatte, Skonti) abgezogen und alle Bezugskosten (wie Fracht und Verpackung) hinzugerechnet wurden, wird als _____ (oder Einstandspreis) bezeichnet.', '', '', 0, 'GAP', 7),
(196, 'In SQL wird ein SELECT-Statement verwendet, um Daten aus Tabellen zu lesen. Welche Anweisung liest alle Spalten einer Tabelle customer aus?', NULL, NULL, 0, 'MC', 8),
(197, 'Ein Primärschlüssel stellt Eindeutigkeit sicher. Welche Eigenschaft trifft nicht auf einen Primärschlüssel zu?', NULL, NULL, 0, 'MC', 8),
(198, 'Das WHERE-Statement dient der Filterung. Welche Abfrage liefert alle Kunden mit age > 30?', NULL, NULL, 0, 'MC', 8),
(199, 'Ein JOIN verbindet Tabellen basierend auf Beziehungen. Welche JOIN-Art liefert nur Zeilen mit passendem Match in beiden Tabellen?', NULL, NULL, 0, 'MC', 8),
(200, 'GROUP BY wird zur Aggregation genutzt. Welche Spalte muss im GROUP BY stehen?', NULL, NULL, 0, 'MC', 8),
(201, 'Aggregatfunktionen berechnen Werte über Zeilen hinweg. Welche der folgenden Funktionen sind Aggregatfunktionen? (Mehrfachauswahl)', NULL, NULL, 1, 'MC', 8),
(202, 'Transaktionen bündeln SQL-Operationen. Welche Anweisungen gehören zu Transaktionen? (Mehrfachauswahl)', NULL, NULL, 1, 'MC', 8),
(203, 'Um eine Ausgabe aus einer oder mehreren Tabellen in der absteigende Reihenfolge aufzulisten, verwendet man', NULL, NULL, 0, 'MC', 8),
(204, 'UPDATE verändert bestehende Zeilen. Welche Teile gehören zu einem vollständigen UPDATE?', NULL, NULL, 1, 'MC', 8),
(205, 'SQL-Tabellen nutzen definierte Datentypen. Welche gehören zu SQL-Standarddatentypen? (Mehrfachauswahl)', NULL, NULL, 1, 'MC', 8),
(206, 'Die Normalisierung reduziert Redundanz. Welche Normalform verlangt atomare Werte?', NULL, NULL, 0, 'MC', 8),
(207, 'SQL nutzt bestimmte Schlüsselwörter zum Filtern. Wähle das passende Schlüsselwort.', NULL, NULL, 0, 'MC', 8),
(208, 'SQL kennt unterschiedliche Delete-Operationen. Welche Operation löscht alle Zeilen und ist schneller als DELETE?', NULL, NULL, 0, 'MC', 8),
(209, 'Stored Procedures speichern SQL-Logik. Was zeichnet Stored Procedures aus? (Mehrfachauswahl)', NULL, NULL, 1, 'MC', 8),
(210, 'In SQL gibt es ein spezielles Schlüsselwort, das verwendet wird, um sicherzustellen, dass eine Abfrage nur eindeutige Werte aus einer Spalte zurückgibt.', NULL, NULL, 0, 'MC', 8),
(211, 'Ein PRIMARY KEY darf doppelte Werte enthalten.', NULL, NULL, 0, 'TF', 8),
(212, 'Ein FOREIGN KEY verweist auf einen PRIMARY KEY einer anderen Tabelle.', NULL, NULL, 0, 'TF', 8),
(213, 'SQL ist eine deklarative Sprache.', NULL, NULL, 0, 'TF', 8),
(214, 'SQL verwendet Schlüsselwörter zur Datenanalyse.', NULL, NULL, 0, 'TF', 8),
(215, 'DELETE löscht die gesamte Tabelle.', NULL, NULL, 0, 'TF', 8),
(216, 'Ein LEFT JOIN liefert auch Zeilen ohne Match.', NULL, NULL, 0, 'TF', 8),
(217, 'Ein Index kann Abfragen beschleunigen.', NULL, NULL, 0, 'TF', 8),
(218, 'NOT NULL bedeutet, dass ein Wort leer sein darf.', NULL, NULL, 0, 'TF', 8),
(219, 'COUNT(*) zählt nur nicht-NULL Werte.', NULL, NULL, 0, 'TF', 8),
(220, 'Ein View speichert keine Daten, sondern eine Abfrage.', NULL, NULL, 0, 'TF', 8),
(221, 'Ein UNIQUE-Constraint verhindert NULL-Werte.', NULL, NULL, 0, 'TF', 8),
(222, 'Tabellen können mehrere FOREIGN KEYS besitzen.', NULL, NULL, 0, 'TF', 8),
(223, 'DISTINCT entfernt doppelte Werte.', NULL, NULL, 0, 'TF', 8),
(224, 'Der Operator für Mustervergleiche lautet_____', '', '', 0, 'GAP', 8),
(225, 'Die Klausel, die die Anzahl der Zeilen reduziert, heißt_____.', '', '.', 0, 'GAP', 8),
(226, 'Mit_____werden neue Zeilen eingefügt.', '', 'werden neue Zeilen eingefügt.', 0, 'GAP', 8),
(227, 'JOIN-Bedingungen stehen üblicherweise nach dem Schlüsselwort_____.', '', '.', 0, 'GAP', 8),
(228, 'Eine SQL-Abfrage endet mit einem_____.', '', '.', 0, 'GAP', 8),
(229, 'Ein Index wird mit_____erstellt', '', 'erstellt', 0, 'GAP', 8),
(230, 'Die Klausel_____sortiert Abfrageergebnisse.', '', 'sortiert Abfrageergebnisse.', 0, 'GAP', 8),
(231, 'Mit_____können Zeilen gruppiert werden.', '', 'können Zeilen gruppiert werden.', 0, 'GAP', 8),
(232, 'Die Funktion_____berechnet den Durchschnitt.', '', 'berechnet den Durchschnitt.', 0, 'GAP', 8),
(233, 'Welche Aussage zur 2. Normalform (2NF) ist korrekt?', NULL, NULL, 0, 'MC', 9),
(234, 'Welche Aussagen zur Normalisierung sind korrekt?', NULL, NULL, 1, 'MC', 9),
(235, 'Welche SQL-Statements sind syntaktisch korrekt und sinnvoll?', NULL, NULL, 1, 'MC', 10),
(236, 'Welche Aussagen zur Umsetzung von Beziehungen im relationalen Modell sind korrekt?', NULL, NULL, 1, 'MC', 11),
(237, 'Ein Fremdschlüssel kann auf einen Primärschlüssel oder auf einen UNIQUE-Constraint einer anderen Tabelle zeigen.', NULL, NULL, 0, 'TF', 11),
(238, 'Ein JOIN in SQL ist ausschließlich für die Anzeige von Daten notwendig, er ändert die Tabellenstruktur nicht.', NULL, NULL, 0, 'TF', 12),
(239, 'Ein LEFT JOIN liefert nur Datensätze, die in beiden Tabellen übereinstimmen.', NULL, NULL, 0, 'TF', 12),
(240, 'Ein Subquery in der WHERE-Klausel kann mehrere Werte zurückgeben, wenn die Bedingung = verwendet wird.', NULL, NULL, 0, 'TF', 12),
(241, 'Gegeben sind die Tabellen kunde(id, name) und bestellung(id, kunden_id, betrag). Gesucht wird die Gesamtsumme aller Bestellungen pro Kunde auch wenn ein Kunde keine Bestellungen hat. SELECT k._____, SUM(b., SUM(b._____) FROM) FROM_____k LEFT JOINk LEFT JOIN_____b ON k.id = b.kunden_id GROUP BY k.b ON k.id = b.kunden_id GROUP BY k._____;', '', '', 0, 'GAP', 12),
(242, 'Die_____beschreibt einebeschreibt eine_____zwischen zwei Entitäten. Einezwischen zwei Entitäten. Eine_____-Beziehung bedeutet zum Beispiel, dass ein Datensatz der ersten Entität mehreren Datensätzen der zweiten Entität zugeordnet sein kann. Diese Beziehung wird in relationalen Tabellen durch einen-Beziehung bedeutet zum Beispiel, dass ein Datensatz der ersten Entität mehreren Datensätzen der zweiten Entität zugeordnet sein kann. Diese Beziehung wird in relationalen Tabellen durch einen_____auf derauf der_____-Seite umgesetzt.', '', '', 0, 'GAP', 11),
(243, 'Welche Aussage zur 3. Normalform (3NF) ist korrekt?', NULL, NULL, 0, 'MC', 9),
(244, 'Welche Aussagen zu Primärschlüssel und UNIQUE sind korrekt?', NULL, NULL, 1, 'MC', 13),
(245, 'Welche Aussagen zu Indizes sind korrekt?', NULL, NULL, 1, 'MC', 13),
(246, 'Welche Aussagen zu GROUP BY und Aggregatfunktionen sind korrekt?', NULL, NULL, 1, 'MC', 10),
(247, 'Ein Fremdschlüssel darf NULL sein, wenn die Beziehung optional ist.', NULL, NULL, 0, 'TF', 11),
(248, 'Die WHERE-Klausel wird nach der GROUP BY-Klausel ausgeführt und kann aggregierte Werte filtern.', NULL, NULL, 0, 'TF', 10),
(249, 'Ein INNER JOIN liefert nur Datensätze, für die in beiden Tabellen passende Zeilen existieren.', NULL, NULL, 0, 'TF', 12),
(250, 'Ein UNIQUE-Constraint erlaubt in SQL niemals mehrere NULL-Werte in derselben Spalte.', NULL, NULL, 0, 'TF', 13),
(251, 'Ein_____ist ein Attribut (oder eine Attributkombination), das einen Datensatz eindeutig identifiziert. Einist ein Attribut (oder eine Attributkombination), das einen Datensatz eindeutig identifiziert. Ein_____verweist auf einen Datensatz in einer anderen Tabelle und stellt so eineverweist auf einen Datensatz in einer anderen Tabelle und stellt so eine_____zwischen Tabellen her.', '', '', 0, 'GAP', 11),
(252, 'Gegeben sind die Tabellen produkt(id, name, preis) und verkauf(id, produkt_id, menge). Gesucht wird der Gesamtumsatz pro Produkt (menge * preis). Produkte ohne Verkäufe sollen trotzdem angezeigt werden. SELECT p._____, COALESCE(SUM(v., COALESCE(SUM(v._____* p.* p._____), 0) AS umsatz FROM), 0) AS umsatz FROM_____p LEFT JOINp LEFT JOIN_____v ON p.id = v.produkt_id GROUP BY p.v ON p.id = v.produkt_id GROUP BY p._____;', '', '', 0, 'GAP', 12),
(253, 'Welche SQL-Statements sind korrekt', NULL, NULL, 1, 'MC', 14),
(254, 'Welche Aussagen zu Datentypen sind korrekt?', NULL, NULL, 1, 'MC', 13),
(255, 'Welche Aggregatfunktionen gibt es?', NULL, NULL, 1, 'MC', 10),
(256, 'Welche Aussage zu WHERE und HAVING ist korrekt?', NULL, NULL, 0, 'MC', 10),
(257, 'COALESCE gibt den ersten nicht-NULL Wert zurück', NULL, NULL, 0, 'TF', 10),
(258, 'COUNT(*) zählt nur Nicht-NULL Werte', NULL, NULL, 0, 'TF', 10),
(259, 'AVG berücksichtigt NULL-Werte bei der Durchschnittsberechnung', NULL, NULL, 0, 'TF', 10),
(260, 'LIMIT begrenzt die Anzahl der ausgegebenen Zeilen', NULL, NULL, 0, 'TF', 10),
(261, 'LIKE verwendet_____als Wildcard undals Wildcard und_____als Platzhalter für genau ein Zeichen', '', '', 0, 'GAP', 10),
(262, 'Vervollständige folgenden SQL-Trigger, der nach einem UPDATE die alten Werte eines Mitarbeiters in eine Log-Tabelle speichert. CREATE_____log_changeslog_changes_____UPDATE ON employeesUPDATE ON employees_____EACH ROW BEGIN INSERT INTO employees_log (employee_id, name, action) VALUES (OLD.employee_id, OLD.name, \'updated\'); END;', '', '', 0, 'GAP', 14),
(263, 'Wofür steht ACID?', NULL, NULL, 0, 'MC', 14),
(264, 'Welche Aussagen über Trigger in SQL sind zutreffend?', NULL, NULL, 1, 'MC', 14),
(265, 'Welche Eigenschaft kennzeichnet eine Transaktion im Datenbankkontext (ACID)?', NULL, NULL, 1, 'MC', 14),
(266, 'Was ist der Hauptunterschied zwischen DROP und DELETE?', NULL, NULL, 0, 'MC', 14),
(267, 'Mit dem REVOKE-Befehl können einem Benutzer zuvor erteilte Rechte wieder entzogen werden.', NULL, NULL, 0, 'TF', 13),
(268, 'Ein INNER JOIN und ein WHERE-Join (verknüpfte Tabellen in der WHERE-Klausel) sind funktional identisch.', NULL, NULL, 0, 'TF', 12),
(269, 'Ein TRUNCATE TABLE-Befehl kann durch ein ROLLBACK rückgängig gemacht werden.', NULL, NULL, 0, 'TF', 14),
(270, 'Ein DEFAULT-Wert in einer Tabellenspalte verhindert die Eingabe von NULL-Werten.', NULL, NULL, 0, 'TF', 14),
(271, 'Vervollständige das SQL-Statement: Zeige alle Kunden an, die noch nie eine Bestellung aufgegeben haben SELECT k.* FROM kunde k_______________b ON k.id = b.kunden_id WHERE b.idb ON k.id = b.kunden_id WHERE b.id__________;', '', '', 0, 'GAP', 12),
(272, 'Vervollständige das SQL-Statement: Erstelle eine Tabelle mitarbeiter mit den Spalten id (Primärschlüssel, automatisch hochzählend) und name (Pflichtfeld)__________mitarbeiter( idmitarbeiter( id____________________, name, name_____((_____))__________);', '', '', 0, 'GAP', 14),
(273, 'Welche Aussage zu GROUP BY ist korrekt?', NULL, NULL, 0, 'MC', 10),
(274, 'Welche Aussagen zu Fremdschlüsseln sind korrekt?', NULL, NULL, 1, 'MC', 11),
(275, 'Welche Aussagen zu Normalformen sind korrekt?', NULL, NULL, 1, 'MC', 9),
(276, 'Welche Aussagen zu Transaktionen sind korrekt?', NULL, NULL, 1, 'MC', 14),
(277, 'Welche Aussagen zu JOIN-Typen sind korrekt?', NULL, NULL, 1, 'MC', 12),
(278, 'Welche Aussagen zu Indizes sind korrekt?', NULL, NULL, 1, 'MC', 13),
(279, 'Eine Tabelle kann mehrere Fremdschlüssel besitzen.', NULL, NULL, 0, 'TF', 11),
(280, 'HAVING kann ohne GROUP BY verwendet werden.', NULL, NULL, 0, 'TF', 10),
(281, 'Ein CHECK-Constraint kann Wertebereiche für eine Spalte einschränken.', NULL, NULL, 0, 'TF', 14),
(282, 'Ein INDEX garantiert automatisch die Eindeutigkeit der Werte.', NULL, NULL, 0, 'TF', 13),
(283, 'Gegeben ist die Tabelle bestellung(id, kunden_id, betrag). Zeige alle kunden_id an, deren Gesamtbestellwert größer als 1000 ist. SELECT kunden_id, SUM(betrag) FROM_____GROUP BYGROUP BY__________SUM(betrag) > 1000;', '', '', 0, 'GAP', 10),
(284, 'Vervollständige das SQL-Statement. Beim Löschen eines Kunden sollen automatisch alle zugehörigen Bestellungen gelöscht werden. CREATE TABLE bestellung ( id INT PRIMARY KEY, kunden_id INT, FOREIGN KEY (kunden_id) REFERENCES_____((_____) ON DELETE) ON DELETE_____);', '', '', 0, 'GAP', 11),
(285, 'Welches Entwurfsmuster stellt sicher, dass von einer Klasse nur eine Instanz existiert?', NULL, NULL, 0, 'MC', 15),
(286, 'Welche Zeitkomplexität (Big-O) hat die binäre Suche im Worst-Case?', NULL, NULL, 0, 'MC', 15),
(287, 'Welche Datenstruktur arbeitet nach dem FIFO-Prinzip (First-In-First-Out)?', NULL, NULL, 0, 'MC', 15),
(288, 'Was beschreibt eine Komposition in einem UML-Klassendiagramm?', NULL, NULL, 0, 'MC', 15),
(289, 'Welches SOLID-Prinzip besagt, dass eine Klasse nur einen Grund für Änderungen haben sollte?', NULL, NULL, 0, 'MC', 15),
(290, 'Was passiert beim \""Overloading\"" (Überladen) einer Methode?', NULL, NULL, 0, 'MC', 15),
(291, 'Welcher Sortieralgorithmus nutzt das \""Divide and Conquer\""-Verfahren?', NULL, NULL, 0, 'MC', 15),
(292, 'In einem PAP (Programmablaufplan) steht ein Parallelogramm für?', NULL, NULL, 0, 'MC', 15),
(293, 'Was ist ein \""Pointer\"" (Zeiger)?', NULL, NULL, 0, 'MC', 15),
(294, 'Was beschreibt das \""Liskovsche Substitutionsprinzip\""?', NULL, NULL, 0, 'MC', 15),
(295, 'Welche Fehlermeldung tritt auf, wenn auf ein Objekt zugegriffen wird, das nicht instanziiert wurde?', NULL, NULL, 0, 'MC', 15),
(296, 'Was ist der Vorteil eines Binärbaums gegenüber einer linearen Liste?', NULL, NULL, 0, 'MC', 15),
(297, 'Wofür steht das \""M\"" im MVC-Entwurfsmuster?', NULL, NULL, 0, 'MC', 15),
(298, 'Welches Keyword verhindert in Java, dass eine Klasse weiter vererbt werden kann?', NULL, NULL, 0, 'MC', 15),
(299, 'Lückentext 1.1Eine Klasse, von der kein Objekt erzeugt werden kann und die als Bauplan für Unterklassen dient, nennt man_____Klasse.', '', '', 0, 'GAP', 15),
(300, 'Lückentext 2Der Zugriffsschutz_____bewirkt, dass nur die Klasse selbst und ihre Unterklassen auf ein Attribut zugreifen können.', '', '', 0, 'GAP', 15),
(301, 'Lückentext 3Das Gegenteil von iterativer Programmierung (Schleifen) ist die_____Programmierung.', '', '', 0, 'GAP', 15),
(302, 'Lückentext 4In der UML-Modellierung wird eine Vererbung durch einen Pfeil mit einer_____Spitze dargestellt.', '', '', 0, 'GAP', 15),
(303, 'Lückentext 5Ein Algorithmus mit der Zeitkomplexität $O(n^2)$ wächst bei Verdopplung der Eingabemenge um den Faktor_____.', '', '', 0, 'GAP', 15),
(304, 'Lückentext 6Die Datenstruktur_____unktioniert nach dem LIFO-Prinzip (Last-In-First-Out).', '', '', 0, 'GAP', 15),
(305, 'Lückentext 7Wenn eine Unterklasse eine Methode der Oberklasse mit exakt derselben Signatur neu implementiert, nennt man das_____.', '', '', 0, 'GAP', 15),
(306, 'Lückentext 8Das Design Pattern, welches Objekte über Zustandsänderungen eines anderen Objekts informiert, heißt_____Pattern.', '', '', 0, 'GAP', 15),
(307, 'Lückentext 9Ein_____ist ein spezieller Typ, der nur eine definierte Menge an festen Werten (Konstanten) annehmen kann.', '', '', 0, 'GAP', 15),
(308, 'Lückentext 10Den Vorgang, Quellcode in Maschinencode zu übersetzen, nennt man_____.', '', '', 0, 'GAP', 15),
(309, 'Lückentet 11Ein_____stellt eine Verbindung zwischen zwei Klassen in UML dar, ohne dass eine Hierarchie besteht.', '', '', 0, 'GAP', 15),
(310, 'Lückentext 12Die_____Suche setzt voraus, dass die Datenmenge bereits sortiert ist.', '', '', 0, 'GAP', 15),
(311, 'Welche Datenstruktur eignet sich besonders gut zur Implementierung von Rekursionen?', NULL, NULL, 0, 'MC', 15),
(312, 'Welche Aussage beschreibt eine Hash-Tabelle am besten?', NULL, NULL, 0, 'MC', 15),
(313, 'Welcher Algorithmus wird häufig zum Finden des kürzesten Weges in einem Graphen verwendet?', NULL, NULL, 0, 'MC', 15),
(314, 'Welche Eigenschaft beschreibt \""Kapselung\"" in der objektorientierten Programmierung?', NULL, NULL, 0, 'MC', 15),
(315, 'Was beschreibt ein Interface in Java am besten?', NULL, NULL, 0, 'MC', 15),
(316, 'Welche Traversierung besucht bei einem Binärbaum zuerst die Wurzel, dann den linken und anschließend den rechten Teilbaum?', NULL, NULL, 0, 'MC', 15),
(317, 'Welcher Datentyp speichert in Java eine Folge von Zeichen?', NULL, NULL, 0, 'MC', 15),
(318, 'Was beschreibt Polymorphismus in der objektorientierten Programmierung?', NULL, NULL, 0, 'MC', 15),
(319, 'Welcher Algorithmus durchsucht zuerst möglichst tief einen Graphen, bevor er zurückgeht?', NULL, NULL, 0, 'MC', 15),
(320, 'Welche Aussage über Bubble Sort ist korrekt?', NULL, NULL, 0, 'MC', 15),
(321, 'Welcher Sortieralgorithmus hat im Durchschnitt eine Zeitkomplexität von $O(n log n)$?', NULL, NULL, 0, 'MC', 15),
(322, 'Welche Eigenschaft beschreibt eine rekursive Methode?', NULL, NULL, 0, 'MC', 15),
(323, 'Was ist ein Graph in der Informatik?', NULL, NULL, 0, 'MC', 15),
(324, 'Welche Aufgabe hat ein Konstruktor in einer Klasse?', NULL, NULL, 0, 'MC', 15),
(325, 'Finally wird immer ausgeführt, unabhängig davon, ob eine Ausnahme aufgetreten ist oder nicht.', NULL, NULL, 0, 'TF', 16),
(326, 'Was wird die Ausgabe des folgenden Programms sein?

class CustomException extends Exception {
    public CustomException(String message) {
        super(message);
    }
}

public class Printer {
    public static void main(String[] args) {
        try {
            throw new CustomException(""Custom error occurred"");
        } catch (CustomException e) {
            System.out.println(e.getMessage());
        }
    }
}', NULL, NULL, 0, 'MC', 16),
(327, 'Welche der folgenden Möglichkeiten ist die korrekte Deklaration eines Arrays in Java?', NULL, NULL, 0, 'MC', 16),
(328, 'Auf das dritte Element des Arrays arr wird mit arr[2] zugegriffen.', NULL, NULL, 0, 'TF', 16),
(329, 'Was wird die Ausgabe des folgenden Codes sein?
class A {
    void display() {
        System.out.println(""Class A"");
    }
}
class B extends A {
    void display() {
        System.out.println(""Class B"");
    }
}
public class Main {
    public static void main(String[] args) {
        A obj = new B();
        obj.display();
    }
}', NULL, NULL, 0, 'MC', 16),
(330, 'Welches Schlüsselwort wird verwendet, um eine Unterklasse in Java zu erstellen?', NULL, NULL, 0, 'MC', 16),
(331, 'Was passiert, wenn eine abstrakte Klasse keine abstrakten Methoden hat?', NULL, NULL, 0, 'MC', 16),
(332, 'Was ist der Standardwert eines boolean in Java?', NULL, NULL, 0, 'MC', 16),
(333, 'Was wird die Ausgabe dieses Codes sein?

int a = 7;
double b = 2;
System.out.println(a / b);', NULL, NULL, 0, 'MC', 16),

    (334, 'Was wird die Ausgabe dieses Codes sein?

byte x = 127;
x++;
System.out.println(x);', NULL, NULL, 0, 'MC', 16),
(335, 'Welche Aussage über final, finally und finalize ist korrekt?', NULL, NULL, 0, 'MC', 17),
(336, 'Wie groß ist der Datentyp char in Java?', NULL, NULL, 0, 'MC', 17),
(337, 'Ausgabe des folgenden Java-Programms:

class Main {
    public static void main(String args[]){
        final int i;
        i = 20;
        System.out.println(i);
    }
}', NULL, NULL, 0, 'MC', 17),
(338, 'Wofür wird das Schlüsselwort final in Java verwendet?', NULL, NULL, 0, 'MC', 17),
(339, 'Was passiert, wenn kein Konstruktor in einer Java-Klasse definiert wird?', NULL, NULL, 0, 'MC', 17),
(340, 'Kann ein Java-Konstruktor privat sein und trotzdem zur Instanziierung verwendet werden?', NULL, NULL, 0, 'TF', 17),
(341, 'Was ist der Zweck eines Konstruktors?', NULL, NULL, 0, 'MC', 17),
(342, 'Welches Schlüsselwort verweist auf das unmittelbare Elternklassenobjekt?', NULL, NULL, 0, 'MC', 17),
(343, 'Worauf verweist das Schlüsselwort this?', NULL, NULL, 0, 'MC', 17),
(344, 'Kompilierung ist ein OOP-Konzept in Java.', NULL, NULL, 0, 'TF', 17),
(345, 'Der Stack hat etwa 1 - 2 MB und die Heap-Größe ist dynamisch.', NULL, NULL, 0, 'TF', 18),
(346, 'Was von folgendem befindet sich auf dem Heap in Java?', NULL, NULL, 0, 'MC', 18),
(347, 'Was wird im Stack gespeichert?', NULL, NULL, 0, 'MC', 18),
(348, 'public static void main(String... args) {
   int a = 5;
   String s = new String(""""Hello"""");
}

Die Variable a wird im _ gespeichert und die Referenzvariable s wird im _ gespeichert.
Das eigentliche String-Objekt wird im _ gespeichert.
', '', '', 0, 'GAP', 18),

    (349, 'Der float ist _ Bytes, der double ist _ Bytes, der int ist _ Bytes und ein char ist _ Bytes in Java auf einem 64-Bit-System.
Der float ist_____Bytes, der double ist_____Bytes, der int ist_____Bytesein char ist_____Bytes', '', '', 0, 'GAP', 18),

    (350, 'Was ist ein Unterschied zwischen int und Integer?', NULL, NULL, 0, 'MC', 18),

    (351, 'switch(x) {
    default:
        System.out.println(""""Hello"""");
}

Akzeptable Typen für x sind _ und _.Akzeptable Typen für x sind_____und_____.', '', '', 0, 'GAP', 18),

    (352, '1  double d1 = 5f;
2  double d2 = 5.0;
3  float f1 = 5f;
4  float f2 = 5.0;

In welcher Zeile tritt zuerst ein Compilerfehler auf?', NULL, NULL, 0, 'MC', 18),

(353, 'Wie erzwingt man die Garbage Collection an einem bestimmten Punkt?', NULL, NULL, 0, 'MC', 18),
(354, 'Welche der folgenden Aussagen über Java-Speicher und Objektlebenszyklus ist korrekt?', NULL, NULL, 0, 'MC', 18),
(355, 'Was bedeutet es, einen Singleton für den Logger zu haben?', NULL, NULL, 0, 'MC', 19),
(356, 'Was ist gemäß Clean-Code-Prinzipien falsch an dieser Methode?\nMehrere Antworten sind korrekt.\n\npublic static void doStuff(int a, int b, boolean flag, String s) {\n    int x = a + b;\n    if(flag) {\n        x *= 2;\n        System.out.println(s + x);\n    } else {\n        for(int i=0;i<3;i++) {\n            x += i;\n            System.out.println(x);\n        }\n    }\n}', NULL, NULL, 1, 'MC', 19),
(357, 'Welche der folgenden Aussagen über Vererbung ist falsch?', NULL, NULL, 0, 'MC', 19),
(358, 'Welche Aussage über Vererbung in der objektorientierten Programmierung ist korrekt?', NULL, NULL, 0, 'MC', 19),
(359, 'Was ist der Hauptzweck eines Debuggers?', NULL, NULL, 0, 'MC', 19),
(360, 'Kapselung in der objektorientierten Programmierung bedeutet, den direkten Zugriff auf bestimmte Daten und Methoden eines Objekts einzuschränken.', NULL, NULL, 0, 'TF', 19),
(361, 'Eine interpretierte Sprache übersetzt das gesamte Programm vor der Ausführung in Maschinencode, während eine kompilierte Sprache den Code Zeile für Zeile ausführt.', NULL, NULL, 0, 'TF', 19),
(362, 'Was ist der Unterschied zwischen einer ArrayList und einem Array? (Alle richtigen Antworten auswählen)', NULL, NULL, 1, 'MC', 19),
(363, 'Was ist Polymorphismus in der objektorientierten Programmierung?', NULL, NULL, 0, 'MC', 19),
(364, 'In der objektorientierten Programmierung wird ein Konstruktor automatisch aufgerufen, wenn ein Objekt erstellt wird.', NULL, NULL, 0, 'TF', 19),
(365, 'Zwei Variablen, die auf dasselbe Objekt im Speicher verweisen, spiegeln beide Änderungen wider, die über eine der beiden Variablen vorgenommen werden.', NULL, NULL, 0, 'TF', 20),
(366, 'Hochsprachen werden direkt auf der Hardware ohne Übersetzung ausgeführt.', NULL, NULL, 0, 'TF', 20),
(367, 'Ein Programm, das erfolgreich kompiliert wird, läuft garantiert ohne Fehler.', NULL, NULL, 0, 'TF', 20),
(368, 'Ein Deadlock kann auftreten, wenn mehrere Threads unbegrenzt auf Ressourcen warten, die jeweils von den anderen gehalten werden.', NULL, NULL, 0, 'TF', 20),
(369, 'Welcher Faktor bestimmt hauptsächlich die Effizienz eines Algorithmus?', NULL, NULL, 0, 'MC', 20),
(370, 'Was ist der Hauptzweck von Versionskontrollsystemen?', NULL, NULL, 0, 'MC', 20),
(371, 'Welche Datenbankoperation wird verwendet, um bestehende Daten zu ändern?', NULL, NULL, 0, 'MC', 20),
(372, 'Welches Protokoll wird hauptsächlich für sichere Webkommunikation verwendet?', NULL, NULL, 0, 'MC', 20),
(373, 'Warum wird die Big-O-Notation hauptsächlich in der Informatik verwendet?', NULL, NULL, 0, 'MC', 20),
(374, 'Was ist der Hauptzweck des Prozess-Schedulings?', NULL, NULL, 0, 'MC', 20),
(375, 'Darf ein Primärschlüssel NULL enthalten.', NULL, NULL, 0, 'TF', 21),
(376, 'Normalisierung kann Abfragen manchmal langsamer machen.', NULL, NULL, 0, 'TF', 21),
(377, 'LEFT JOIN liefert auch Zeilen der linken Tabelle ohne entsprechenden Match.', NULL, NULL, 0, 'TF', 30),
(378, 'WHERE filtert vor GROUP BY.', NULL, NULL, 0, 'TF', 30),
(379, 'HAVING ohne GROUP BY ist möglich.', NULL, NULL, 0, 'TF', 30),
(380, 'COUNT(*) zählt auch Zeilen, in denen alles NULL ist.', NULL, NULL, 0, 'TF', 30),
(381, 'COUNT(spalte) zählt Zeilen, in denen alles NULL ist, mit.', NULL, NULL, 0, 'TF', 30),
(382, 'INNER JOIN und JOIN sind gleichbedeutend.', NULL, NULL, 0, 'TF', 30),
(383, 'Transaktionen verhindern parallele Änderungen in derselben Zeile.', NULL, NULL, 0, 'TF', 30),
(384, 'DELETE FROM t; und TRUNCATE t; sind immer gleich.', NULL, NULL, 0, 'TF', 30),
(385, 'Rollback kann Änderungen rückgängig machen.', NULL, NULL, 0, 'TF', 30),
(386, 'Ein Primärschlüssel muss eindeutig sein.', NULL, NULL, 0, 'TF', 21),
(387, 'Ein Fremdschlüssel verhindert automatisch doppelte Werte in der Fremdschlüssel-Spalte.', NULL, NULL, 0, 'TF', 21),
(388, 'In einer 1:n-Beziehung liegt der Fremdschlüssel auf der n-Seite.', NULL, NULL, 0, 'TF', 21),
(389, 'Normalisierung reduziert Datenredundanz.', NULL, NULL, 0, 'TF', 21),
(390, 'Indizes machen Schreibvorgänge (Insert/Update/Delete) grundsätzlich schneller.', NULL, NULL, 0, 'TF', 30),
(391, 'Ein Default-Wert wird genutzt, wenn beim Insert kein Wert geliefert wird.', NULL, NULL, 0, 'TF', 30),
(392, 'Ein Audit-Log ist dasselbe wie ein Backup.', NULL, NULL, 0, 'TF', 30),
(393, 'Ein Backup schützt vor Datenverlust durch „DROP TABLE“ oder versehentliches Löschen.', NULL, NULL, 0, 'TF', 30),
(394, 'Datenbank-Migrationen sind nur bei großen Firmen sinnvoll.', NULL, NULL, 0, 'TF', 30),
(395, 'In der Anwendung sollte man Eingaben validieren.', NULL, NULL, 0, 'TF', 30),
(396, '1NF verbietet mehrere Werte in einer Spalte (z. B. Listen in einer Zelle).', NULL, NULL, 0, 'TF', 21),
(397, '2NF ist nur bei zusammengesetzten Primärschlüsseln relevant.', NULL, NULL, 0, 'TF', 21),
(398, '3NF bedeutet „keine Abhängigkeit von Nicht-Schlüsselattributen“.', NULL, NULL, 0, 'TF', 21),
(399, 'Denormalisierung reduziert Redundanz.', NULL, NULL, 0, 'TF', 21),
(400, 'SELECT gehört zu DQL.', NULL, NULL, 0, 'TF', 30),
(401, 'Eine Transaktion kann mehrere DML-Operationen zusammenfassen.', NULL, NULL, 0, 'TF', 30),
(402, 'Welche Aggregation zählt nur nicht-NULL (gefüllte) Werte in email?', NULL, NULL, 0, 'MC', 30),
(403, 'Welche Klausel filtert nach dem Gruppieren?', NULL, NULL, 0, 'MC', 30),
(404, 'Welche Abfrage ist korrekt, um nach Datum absteigend zu sortieren?', NULL, NULL, 0, 'MC', 30),
(405, 'Was liefert DISTINCT?', NULL, NULL, 0, 'MC', 30),
(406, 'Was beschreibt eine n:m-Beziehung korrekt?', NULL, NULL, 0, 'MC', 21),
(407, 'Welche Eigenschaft ist typisch für einen Primary Key?', NULL, NULL, 0, 'MC', 21),
(408, 'Was stellt ein Foreign Key sicher?', NULL, NULL, 0, 'MC', 21),
(409, 'Was ist ein typisches Ziel von Normalisierung?', NULL, NULL, 0, 'MC', 21),
(410, 'Hauptziel der Normalisierung ist…', NULL, NULL, 0, 'MC', 21),
(411, 'Was ist ein Beispiel für eine Änderungsanomalie?', NULL, NULL, 0, 'MC', 30),
(412, 'Denormalisierung macht man oft, wenn…', NULL, NULL, 0, 'MC', 30),
(413, 'Was ist eine typische Nebenwirkung vieler Indizes?', NULL, NULL, 0, 'MC', 21),
(414, 'Welche Spalte ist häufig ein guter Index-Kandidat?', NULL, NULL, 0, 'MC', 21),
(415, 'Wie schützt man sich am zuverlässigsten gegen SQL-Injection?', NULL, NULL, 0, 'MC', 21),
(416, 'Was ist bei Passwörtern korrekt?', NULL, NULL, 0, 'MC', 21),
(417, 'Welche Beziehung wird typischerweise durch eine Zwischentabelle modelliert?', NULL, NULL, 0, 'MC', 21),
(418, 'Was beschreibt „Kardinalität“?', NULL, NULL, 0, 'MC', 21),
(419, 'Was ist ein „Attribut“ in einem ER-Modell?', NULL, NULL, 0, 'MC', 21),
(420, 'Was ist eine Entität?', NULL, NULL, 0, 'MC', 21),
(421, 'Welche Option ist ein Beispiel für eine schwache Entität?', NULL, NULL, 0, 'MC', 21),
(422, 'Was ist ein zusammengesetzter Primärschlüssel?', NULL, NULL, 0, 'MC', 21),
(423, 'Warum ist 1:1 selten als eigene Tabelle nötig?', NULL, NULL, 0, 'MC', 21);
INSERT INTO `questions` (`Id`, `StartText`, `ImageUrl`, `EndText`, `AllowsMultiple`, `QuestionType`, `QuestionSetId`) VALUES
(424, 'Was bedeutet „optional“ in einer Beziehung?', NULL, NULL, 0, 'MC', 21),
(425, 'Ein typisches Symptom schlechter Normalisierung ist…', NULL, NULL, 0, 'MC', 30),
(426, 'Was ist eine „Löschanomalie“?', NULL, NULL, 0, 'MC', 21),
(427, 'Was ist eine „Einfügeanomalie“?', NULL, NULL, 0, 'MC', 21),
(428, 'Wofür ist ein Index primär da?', NULL, NULL, 0, 'MC', 21),
(429, 'Warum können viele Indizes Schreibzugriffe verlangsamen?', NULL, NULL, 0, 'MC', 21),
(430, 'Was bedeutet „Selektivität“ einer Spalte?', NULL, NULL, 0, 'MC', 21),
(431, 'Welche Spalte ist meistens ein schlechter Index-Kandidat?', NULL, NULL, 0, 'MC', 21),
(432, 'Wo gehört der Fremdschlüssel bei 1:n normalerweise hin?', NULL, NULL, 0, 'MC', 30),
(433, 'Ein zusammengesetzter Primary Key besteht aus:', NULL, NULL, 0, 'MC', 21),
(434, 'Welche Aussage passt zu „Datenintegrität“ am besten?', NULL, NULL, 0, 'MC', 21),
(435, 'Ein Beispiel für „Redundanz“ ist:', NULL, NULL, 0, 'MC', 21),
(436, 'Wofür nutzt man NOT NULL?', NULL, NULL, 0, 'MC', 21),
(437, 'Was ist bei „leer“ vs. „NULL“ korrekt?', NULL, NULL, 0, 'MC', 30),
(438, 'Wo sollte Validierung stattfinden?', NULL, NULL, 0, 'MC', 30),
(439, 'Wann brauchst du typischerweise eine Transaktion?', NULL, NULL, 0, 'MC', 30),
(440, 'Was ist das Ziel einer Transaktion?', NULL, NULL, 0, 'MC', 30),
(441, 'Was ist ein typisches Problem ohne Transaktion?', NULL, NULL, 0, 'MC', 30),
(442, 'Was bedeutet „Rollback“?', NULL, NULL, 0, 'MC', 30),
(443, 'Warum ist „alles in eine große Transaktion“ nicht immer gut?', NULL, NULL, 0, 'MC', 30),
(444, 'Was ist ein Index am ehesten?', NULL, NULL, 0, 'MC', 30),
(445, 'Wann bringen Indizes besonders viel?', NULL, NULL, 0, 'MC', 30),
(446, 'Warum können viele Indizes schaden?', NULL, NULL, 0, 'MC', 30),
(447, 'Was ist „Performance“ bei DB?', NULL, NULL, 0, 'MC', 30),
(448, 'Was schützt am besten vor Datenbank-Zugriff durch gestohlene App-Credentials?', NULL, NULL, 0, 'MC', 30),
(449, 'Was ist ein häufiger Sinn von Test-/Staging-Umgebungen für DB?', NULL, NULL, 0, 'MC', 30),
(450, 'Was ist bezüglich des Sicherns richtig?', NULL, NULL, 0, 'MC', 30),
(451, 'Was ist typisch für relationale Datenbanken?', NULL, NULL, 0, 'MC', 21),
(452, 'Ein Vorteil relationaler DBs ist oft:', NULL, NULL, 0, 'MC', 21),
(453, 'Normalform (1NF) verlangt vor allem:', NULL, NULL, 0, 'MC', 21),
(454, 'Was ist ein klassischer Verstoß gegen 1NF?', NULL, NULL, 0, 'MC', 21),
(455, '2NF ist relevant, wenn…', NULL, NULL, 0, 'MC', 21),
(456, 'Ein typischer Verstoß gegen 2NF ist:', NULL, NULL, 0, 'MC', 21),
(457, '3NF zielt besonders darauf ab, zu vermeiden:', NULL, NULL, 0, 'MC', 21),
(458, 'Beispiel: In Tabelle „Bestellung“ stehen kunden_plz und kunden_ort. Der Ort hängt von der PLZ ab. Das ist typischerweise ein Problem für:', NULL, NULL, 0, 'MC', 21),
(459, 'DDL steht für…', NULL, NULL, 0, 'MC', 30),
(460, 'Was gehört zu DDL?', NULL, NULL, 0, 'MC', 30),
(461, 'Was gehört zu DQL?', NULL, NULL, 0, 'MC', 30),
(462, 'Was gehört zu DML?', NULL, NULL, 0, 'MC', 30),
(463, '„Referenzielle Integrität“ bedeutet:', NULL, NULL, 0, 'MC', 21),
(464, 'Wozu dient ein Foreign Key primär?', NULL, NULL, 0, 'MC', 21),
(465, 'Ein UNIQUE-Constraint sorgt für:', NULL, NULL, 0, 'MC', 30),
(466, 'Was ist KEIN Merkmal einer relationalen Datenbank?', NULL, NULL, 0, 'MC', 21),
(467, 'Was ist KEIN Beispiel für eine relationale Datenbank?', NULL, NULL, 0, 'MC', 21),
(468, 'Was sind Bestandteile einer relationalen Datenbank?', NULL, NULL, 0, 'MC', 21),
(469, 'Was ist KEIN Vorteil einer relationalen Datenbank?', NULL, NULL, 0, 'MC', 21),
(470, 'Was ist ein Nachteil von relationalen Datenbanken?', NULL, NULL, 0, 'MC', 21),
(471, 'Was ist ein natürlicher Schlüssel?', NULL, NULL, 0, 'MC', 21),
(472, 'Was ist ein künstlicher Schlüssel?', NULL, NULL, 0, 'MC', 21),
(473, 'Welcher dieser Schlüssel ist ein natürlicher Schlüssel?', NULL, NULL, 0, 'MC', 21),
(474, 'Welcher dieser Schlüssel ist ein künstlicher Schlüssel?', NULL, NULL, 0, 'MC', 21),
(475, 'Welcher dieser Schlüssel ist ein anonymer Schlüssel?', NULL, NULL, 0, 'MC', 21),
(476, 'Welcher dieser Schlüssel ist ein bedeutender Schlüssel?', NULL, NULL, 0, 'MC', 21),
(477, 'Lückentext 1Eine Datenbank ist eine _____ Sammlung von Daten.Sie wird genutzt, damit Daten _____ gespeichert und später schnell wiedergefunden werden können.Im Vergleich zu einer einfachen Datei (z. B. Excel/CSV) kann eine Datenbank besser mit _____ Benutzern gleichzeitig umgehen und hilft dabei, Daten Im Vergleich zu einer einfachen Datei (z. B. Excel/CSV) kann eine Datenbank besser mit mehreren Benutzern gleichzeitig umgehen und hilft dabei, Daten _____ zu halten.Damit Daten korrekt bleiben, kann man Regeln festlegen, z. B. dass bestimmte Felder nicht leer sein dürfen oder dass IDs eindeutig sind. Solche Regeln heißen _____.Wenn man Daten aus mehreren Tabellen miteinander verbindet (z. B. Kunde ↔ Bestellung); nutzt man dafür _____ (Verknüpfungen).Die Anwendung prüft Eingaben, aber die Datenbank sollte ebenfalls Regeln haben, damit auch bei Importen oder Fehlern keine falschen Daten gespeichert werden. Das nennt man _____.', '', '', 0, 'GAP', 21),
(478, 'Lückentext 2Eine Datenbank ist sinnvoll, wenn man Daten _____ verwalten muss, z. B. Kunden, Bestellungen oder Tickets.Wenn Daten doppelt gespeichert werden, kann das zu _____ führen (z. B. an einer Stelle geändert, an anderer vergessen).Eine häufige Beziehung ist: „Ein Kunde kann mehrere Bestellungen haben“. Das nennt man _____.Damit mehrere Änderungen zusammen zuverlässig klappen (z. B. Bestellung anlegen und Positionen dazu speichern); nutzt man _____.Damit Daten nicht verloren gehen, braucht man regelmäßige _____.Wichtig ist außerdem, dass nicht jeder alles darf: Nutzer sollten nur die _____ bekommen, die sie wirklich benötigen. Dies nennt man Least Privilege.', '', '', 0, 'GAP', 21),
(479, 'Lückentext 3 – Welche Datenbanktypen gibt es?Die Merkmale einer _____ sind eine feste Struktur mit Primär- und Fremdschlüsseln und man kann durch SQL abfragen. Dieser Datentyp ist sehr verbreitet.Dagegen stehen die _____. Sie sind nicht-relational. Ihre Struktur ist nicht fest – sie haben kein festes Schema. _____ beinhalten ihre Daten meist als JSON- oder XML-Dokumente. MongoDB ist ein Beispiel. _____ speichern Daten als Schlüssel-Wert-Paare (Key → Value). Redis ist ein Beispiel. _____ speichern Daten spaltenweise (statt zeilenweise) und sind gut für Analysen großer Datenmengen. _____ speichern Daten als Knoten und Kanten und sind gut für stark vernetzte Daten (z. B. soziale Netzwerke). _____ speichern Daten als Objekte inkl. Attributen und Referenzen.', '', '', 0, 'GAP', 21),
(480, 'Was bewirkt die SQL-Anweisung \""SELECT\""?', NULL, NULL, 0, 'MC', 22),
(481, 'Wozu dient ein JOIN?Ein JOIN_____Datensaetze aus mehreren Tabellen ueber gemeinsame_____.', '', '', 0, 'GAP', 22),
(482, 'Wofür wird GROUP BY verwendet?', NULL, NULL, 0, 'MC', 22),
(483, 'Was bedeutet 3.  Normalform?', NULL, NULL, 0, 'MC', 24),
(484, 'Bei der 1. Normalform enthalten alle Attribute atomare Werte und keine Wiederholungsgruppen.', NULL, NULL, 0, 'TF', 24),
(485, 'Was beschreibt ein Entity-Relationship-Modell (ERM)?Das ERM ist ein konzeptionelles Modell, das Objekte der realen Welt (Entities) und ihre Beziehungen grafisch darstellt – unabhängig von einer konkreten Datenbankimplementierung.', NULL, 'Das ERM ist ein konzeptionelles Modell, das Objekte der realen Welt (Entities) und ihre Beziehungen grafisch darstellt – unabhängig von einer konkreten Datenbankimplementierung.', 0, 'MC', 24),
(486, 'Was ist eine Entität im ERM?Eine Entität ist ein eindeutig identifizierbares Objekt der realen Welt, das in der Datenbank abgebildet werden soll. Im ER-Diagramm wird sie als Rechteck dargestellt.', NULL, 'Eine Entität ist ein eindeutig identifizierbares Objekt der realen Welt, das in der Datenbank abgebildet werden soll. Im ER-Diagramm wird sie als Rechteck dargestellt.', 0, 'MC', 24),
(487, 'Was versteht man unter einem Attribut im ERM?Attribute beschreiben Eigenschaften einer Entität oder Beziehung. Im ER-Diagramm als Ellipse dargestellt. Schlüsselattribute werden unterstrichen.', NULL, 'Attribute beschreiben Eigenschaften einer Entität oder Beziehung. Im ER-Diagramm als Ellipse dargestellt. Schlüsselattribute werden unterstrichen.', 0, 'MC', 24),
(488, 'Was ist ein Primärschlüssel?Ein Primärschlüssel identifiziert jeden Datensatz in einer Tabelle eindeutig. Er darf nicht NULL sein und muss für jede Zeile einmalig sein.', NULL, 'Ein Primärschlüssel identifiziert jeden Datensatz in einer Tabelle eindeutig. Er darf nicht NULL sein und muss für jede Zeile einmalig sein.', 0, 'MC', 24),
(489, 'Was ist ein Fremdschlüssel?Ein Fremdschlüssel ist ein Attribut in einer Tabelle, das auf den Primärschlüssel einer anderen Tabelle verweist und damit referentielle Integrität sicherstellt.', NULL, 'Ein Fremdschlüssel ist ein Attribut in einer Tabelle, das auf den Primärschlüssel einer anderen Tabelle verweist und damit referentielle Integrität sicherstellt.', 0, 'MC', 24),
(490, 'Was bedeutet die Kardinalität 1:n in einer Beziehung?Bei einer 1:n-Beziehung kann einem Datensatz auf der 1-Seite mehrere Datensätze auf der n-Seite zugeordnet sein, aber jeder n-Datensatz gehört genau einem 1-Datensatz.', NULL, 'Bei einer 1:n-Beziehung kann einem Datensatz auf der 1-Seite mehrere Datensätze auf der n-Seite zugeordnet sein, aber jeder n-Datensatz gehört genau einem 1-Datensatz.', 0, 'MC', 24),
(491, 'Wie wird eine m:n-Beziehung im relationalen Modell umgesetztEine m:n-Beziehung kann im relationalen Modell nicht direkt abgebildet werden. Sie wird durch eine Zwischentabelle aufgelöst, die die Primärschlüssel beider Tabellen als Fremdschlüssel enthält.', NULL, 'Eine m:n-Beziehung kann im relationalen Modell nicht direkt abgebildet werden. Sie wird durch eine Zwischentabelle aufgelöst, die die Primärschlüssel beider Tabellen als Fremdschlüssel enthält.', 0, 'MC', 24),
(492, 'Was ist ein zusammengesetzter Primärschlüssel?Ein zusammengesetzter Primärschlüssel besteht aus mehreren Attributen, die gemeinsam einen Datensatz eindeutig identifizieren. Kein einzelnes Attribut allein reicht dafür aus.', NULL, 'Ein zusammengesetzter Primärschlüssel besteht aus mehreren Attributen, die gemeinsam einen Datensatz eindeutig identifizieren. Kein einzelnes Attribut allein reicht dafür aus.', 0, 'MC', 24),
(493, 'Was besagt die Erste Normalform (1NF)?1NF fordert atomare Attributwerte – keine Mengen, Listen oder Wiederholungsgruppen in einer Zelle. Eine Zelle enthält genau einen Wert.', NULL, '1NF fordert atomare Attributwerte – keine Mengen, Listen oder Wiederholungsgruppen in einer Zelle. Eine Zelle enthält genau einen Wert.', 0, 'MC', 24),
(494, 'Ein Datenbankfeld enthält den Wert „Müller, Schmidt, Wagner\"" als eine einzige Zeichenkette. Welche Normalform ist verletzt?Der Wert ist nicht atomar – er enthält mehrere Namen in einem Feld. Das verletzt die 1NF, die atomare Werte fordert.', NULL, 'Der Wert ist nicht atomar – er enthält mehrere Namen in einem Feld. Das verletzt die 1NF, die atomare Werte fordert.', 0, 'MC', 24),
(495, 'Was ist Voraussetzung für die Zweite Normalform (2NF)?2NF setzt 1NF voraus. Zusätzlich muss jedes Nicht-Schlüssel-Attribut voll funktional vom gesamten Primärschlüssel abhängen – nicht nur von einem Teil davon (keine partiellen Abhängigkeiten).', NULL, '2NF setzt 1NF voraus. Zusätzlich muss jedes Nicht-Schlüssel-Attribut voll funktional vom gesamten Primärschlüssel abhängen – nicht nur von einem Teil davon (keine partiellen Abhängigkeiten).', 0, 'MC', 24),
(496, 'Eine Tabelle mit dem zusammengesetzten Schlüssel (BestellungID, ArtikelID) enthält das Attribut „KundenName\"", das nur von „BestellungID\"" abhängt. Welche Normalform ist verletzt?KundenName hängt nur von BestellungID ab – einem Teil des zusammengesetzten Primärschlüssels. Das ist eine partielle Abhängigkeit und verletzt die 2NF.', NULL, 'KundenName hängt nur von BestellungID ab – einem Teil des zusammengesetzten Primärschlüssels. Das ist eine partielle Abhängigkeit und verletzt die 2NF.', 0, 'MC', 24),
(497, 'Was beschreibt die Dritte Normalform (3NF)?', NULL, '3NF setzt 2NF voraus und verlangt zusätzlich, dass keine transitiven Abhängigkeiten zwischen Nicht-Schlüssel-Attributen existieren. Kein Nicht-Schlüssel-Attribut darf von einem anderen Nicht-Schlüssel-Attribut abhängen.', 0, 'MC', 24),
(498, 'Eine Tabelle enthält: MitarbeiterID → AbteilungsID → AbteilungsLeiter. Welche Normalform ist verletzt?', NULL, 'AbteilungsLeiter hängt nicht direkt vom Primärschlüssel (MitarbeiterID) ab, sondern transitiv über AbteilungsID. Das verletzt die 3NF.', 0, 'MC', 24),
(499, 'Was ist eine Einfügeanomalie?Ein Problem, bei dem ein neuer_____nicht_____werden kann,ohne gleichzeitig unnötige oder unbekannte_____zu ergänzen.Eine Einfügeanomalie liegt vor, wenn ein neuer Datensatz nicht eingefügt werden kann, ohne gleichzeitig andere, nicht relevante Daten einzutragen – typisches Symptom einer nicht normalisierten Tabelle.', '', 'Eine Einfügeanomalie liegt vor, wenn ein neuer Datensatz nicht eingefügt werden kann, ohne gleichzeitig andere, nicht relevante Daten einzutragen – typisches Symptom einer nicht normalisierten Tabelle.', 0, 'GAP', 24),
(500, 'Was ist eine Löschanomalie?', NULL, 'Eine Löschanomalie tritt auf, wenn beim Löschen eines Datensatzes unbeabsichtigt andere relevante Informationen verloren gehen, weil Daten unnötig zusammengefasst wurden.', 0, 'MC', 24),
(501, 'Was ist eine Änderungsanomalie?', NULL, 'Wenn dieselbe Information mehrfach in einer Tabelle gespeichert ist, muss sie bei einer Änderung an mehreren Stellen manuell aktualisiert werden. Wird eine Stelle vergessen, entstehen inkonsistente Daten.', 0, 'MC', 24),
(502, 'Was versteht man unter referentieller Integrität?Referentielle Integrität bedeutet, dass ein_____entweder NULL istoder auf einen tatsächlich existierenden_____in der referenzierten Tabelle zeigen muss.Referentielle Integrität bedeutet, dass ein Fremdschlüsselwert entweder NULL ist oder auf einen tatsächlich existierenden Primärschlüssel in der referenzierten Tabelle zeigen muss.', '', 'Referentielle Integrität bedeutet, dass ein Fremdschlüsselwert entweder NULL ist oder auf einen tatsächlich existierenden Primärschlüssel in der referenzierten Tabelle zeigen muss.', 0, 'GAP', 24),
(503, 'Was passiert, wenn referentielle Integrität verletzt wird?', NULL, 'Bei einer Verletzung der referentiellen Integrität existiert ein Fremdschlüsselwert, dem kein entsprechender Primärschlüssel in der referenzierten Tabelle gegenübersteht – ein sogenannter Dangling Reference.', 0, 'MC', 24),
(504, 'Eine schwache Entität kann durch eigene Attribute alleine eindeutig identifiziert werden. Sie ist für ihre Existenz und Identifikation auf eine starke Entität angewiesen. Im ER-Diagramm als doppeltes Rechteck dargestellt.', NULL, 'Eine schwache Entität kann nicht durch eigene Attribute alleine eindeutig identifiziert werden. Sie ist für ihre Existenz und Identifikation auf eine starke Entität angewiesen. Im ER-Diagramm als doppeltes Rechteck dargestellt.', 0, 'TF', 24),
(505, 'Was ist eine rekursive Beziehung im ERM?', NULL, 'Eine rekursive (unäre) Beziehung verbindet eine Entität mit sich selbst. Klassisches Beispiel: Ein Mitarbeiter kann Vorgesetzter anderer Mitarbeiter sein – beides sind Instanzen derselben Entität.', 0, 'MC', 24),
(506, 'Was ist ein Schlüsselkandidat (Candidate Key)?', NULL, 'Ein Kandidatenschlüssel ist jede minimale Attributkombination, die alle Zeilen einer Tabelle eindeutig identifizieren kann. Aus allen Kandidatenschlüsseln wird einer als Primärschlüssel ausgewählt.', 0, 'MC', 24),
(507, 'Was unterscheidet einen natürlichen Schlüssel von einem Surrogatschlüssel?', NULL, 'Ein natürlicher Schlüssel ist ein fachliches Attribut mit eigener Bedeutung (z.B. Steuernummer, ISBN). Ein Surrogatschlüssel ist ein künstlich erzeugter Wort ohne fachliche Bedeutung (z.B. auto-increment ID).', 0, 'MC', 24),
(508, 'Wie wird eine 1:1-Beziehung im relationalen Modell typischerweise umgesetzt?', NULL, 'Bei einer 1:1-Beziehung kann der Primärschlüssel einer Tabelle als Fremdschlüssel in der anderen eingetragen werden, oder beide Entitäten werden zu einer einzigen Tabelle zusammengeführt.', 0, 'MC', 24),
(509, 'Was beschreibt Funktionale Abhängigkeit im Kontext der Normalisierung?', NULL, 'Attribut B ist funktional abhängig von Attribut A (A → B), wenn jeder Wert von A genau einen Wert von B bestimmt. Dies ist die Grundlage aller Normalformen.', 0, 'MC', 24),
(510, 'Welche Modellierungsregel gilt beim Überführen eines ERM ins relationale Modell für m:n-Beziehungen?', NULL, 'm:n-Beziehungen können im relationalen Modell nicht direkt abgebildet werden. Es wird eine eigene Zwischentabelle erstellt, die die Primärschlüssel beider Entitäten als Fremdschlüssel und ggf. eigene Beziehungsattribute enthält.', 0, 'MC', 24),
(511, 'Warum sollte man NULL-Werte bei Primärschlüsseln verbieten?', NULL, 'Ein Primärschlüssel muss jeden Datensatz eindeutig identifizieren können. NULL bedeutet \'unbekannt\' und erlaubt keine eindeutige Identifikation – daher ist NULL in Primärschlüsseln grundsätzlich verboten.', 0, 'MC', 24),
(512, 'Was ist der Unterschied zwischen einem konzeptionellen und einem logischen Datenmodell?', NULL, 'Das konzeptionelle Modell (ERM) beschreibt fachliche Zusammenhänge unabhängig von Technik und Implementierung. Das logische Modell (relationales Schema) überführt das ERM in konkrete Tabellenstrukturen.', 0, 'MC', 24),
(513, 'Was versteht man unter Denormalisierung?', NULL, 'Denormalisierung ist das bewusste Einführen von Redundanz in ein normalisiertes Schema, um Leseperformance zu steigern. Dabei werden Tabellen zusammengeführt oder Daten dupliziert – auf Kosten der Datenkonsistenz.', 0, 'MC', 24),
(514, 'Welche Kardinalitätsnotation drückt aus, dass ein Kunde mindestens eine, aber beliebig viele Bestellungen haben kann?', NULL, 'Die Notation 1:n (bzw. in Min-Max-Notation (1,1) auf Kundenseite und (1,n) auf Bestellungsseite) drückt aus, dass jeder Kunde mindestens eine Bestellung hat und beliebig viele haben kann.', 0, 'MC', 24),
(515, 'Was bedeutet die Min-Max-Notation (0,1) bei einer Beziehung?', NULL, 'Die Notation (0,1) bedeutet, dass die Entität an der Beziehung mit keinem oder genau einem Partner beteiligt sein kann – die Teilnahme ist also optional, aber höchstens einmal möglich.', 0, 'MC', 24),
(516, 'Ein Attribut enthält sowohl Straße als auch Hausnummer als einen gemeinsamen String. Welche Lösung entspricht der 1NF?', NULL, 'Die 1NF fordert atomare Werte. Straße und Hausnummer sind zwei verschiedene Informationen und müssen in separate Attribute aufgeteilt werden.', 0, 'MC', 24),
(517, 'Was ist ein zusammengesetztes Attribut im ERM?', NULL, 'Ein zusammengesetztes Attribut besteht aus mehreren Teilattributen, z.B. ist Adresse zusammengesetzt aus Straße, PLZ und Ort. Im ER-Diagramm verzweigt sich die Ellipse in Teilellipsen.', 0, 'MC', 24),
(518, 'Was ist ein mehrwertiges Attribut im ERM?', NULL, 'Ein mehrwertiges Attribut kann für eine Entität mehrere Werte annehmen, z.B. kann ein Kunde mehrere Telefonnummern haben. Im ER-Diagramm durch eine doppelte Ellipse dargestellt.', 0, 'MC', 24),
(519, 'Wie wird ein mehrwertiges Attribut im relationalen Modell korrekt abgebildet?', NULL, 'Mehrwertige Attribute können nicht direkt in einer Spalte gespeichert werden (das würde 1NF verletzen). Sie werden in eine eigene Tabelle ausgelagert mit einem Fremdschlüssel auf die Ursprungsentität.', 0, 'MC', 24),
(520, 'Was ist der Unterschied zwischen einer Entität und einem Entitätstyp?', NULL, 'Ein Entitätstyp beschreibt die Klasse aller gleichartigen Objekte (z.B. \'Kunde\' als Konzept). Eine Entität ist eine konkrete Instanz dieses Typs (z.B. der Kunde \'Müller mit KundenID 42\').', 0, 'MC', 24),
(521, 'Warum werden Beziehungen im ERM in eigene Tabellen überführt, auch wenn sie nur Fremdschlüssel enthalten?', NULL, 'Bei m:n-Beziehungen ist eine Zwischentabelle technisch notwendig, da das relationale Modell keine direkten m:n-Beziehungen unterstützt. Nur so können die Verknüpfungen ohne Redundanz abgebildet werden.', 0, 'MC', 24),
(522, 'Was ist ein abgeleitetes Attribut im ERM?', NULL, 'Ein abgeleitetes Attribut ist ein Attribut, dessen Wert aus anderen gespeicherten Attributen berechnet werden kann. Es wird im ER-Diagramm durch eine gestrichelte Ellipse dargestellt und muss nicht physisch gespeichert werden.', 0, 'MC', 24),
(523, 'Welche Situation ist ein typisches Zeichen für eine fehlende Normalisierung?', NULL, 'Wenn dieselbe Information – z.B. eine Kundenadresse – in mehreren Zeilen wiederholt gespeichert wird, deutet das auf fehlende Normalisierung hin. Jede Änderung muss dann an mehreren Stellen vorgenommen werden.', 0, 'MC', 24),
(524, 'Gegeben ist ein ERM mit den Entitäten „Student\"" und „Kurs\"" in einer m:n-Beziehung „belegt\"". Welche Tabellen entstehen beim Überführen ins relationale Modell?', NULL, 'Aus den zwei Entitäten werden zwei Tabellen (Student, Kurs). Die m:n-Beziehung wird durch eine dritte Tabelle (z.B. Belegung) aufgelöst, die StudentID und KursID als Fremdschlüssel enthält.', 0, 'MC', 24),
(525, 'Quellcode ist automatisch durch das Urheberrecht geschützt, auch ohne Registrierung.', NULL, 'Quellcode ist automatisch urheberrechtlich geschützt.', 0, 'TF', 25),
(526, 'Ein Werkvertrag verpflichtet den Auftragnehmer zur Erbringung eines bestimmten Erfolgs.', NULL, 'Ein Werkvertrag schuldet einen Erfolg.', 0, 'TF', 25),
(527, 'Welche Aussage beschreibt eine AGB am besten?', NULL, 'AGB sind vorformulierte Vertragsbedingungen.', 0, 'MC', 25),
(528, 'Welche Lizenz erlaubt die kommerzielle Nutzung ohne Einschränkungen?', NULL, 'Die MIT‑Lizenz erlaubt kommerzielle Nutzung ohne Einschränkungen.', 0, 'MC', 25),
(529, 'Welche Pflicht ergibt sich aus der DSGVO für Unternehmen?', NULL, 'Datenminimierung ist eine Pflicht der DSGVO.', 0, 'MC', 25),
(530, 'Bei einem_____vertrag schuldet der Auftragnehmer keinen Erfolg, sondern nur eine Tätigkeit.Bei einem **Dienstvertrag** schuldet der Auftragnehmer keinen Erfolg.', '', 'Bei einem **Dienstvertrag** schuldet der Auftragnehmer keinen Erfolg.', 0, 'GAP', 25),
(531, 'Das_____recht schützt Softwareentwickler vor unerlaubter Nutzung ihres Codes.Das **Urheberrecht** schützt Softwareentwickler.', '', 'Das **Urheberrecht** schützt Softwareentwickler.', 0, 'GAP', 25),
(532, 'Personenbezogene Daten dürfen nur verarbeitet werden,wenn eine_____vorliegt.', '', '', 0, 'GAP', 25),
(533, 'Ein Kunde kann bei mangelhafterSoftware_____verlangen.', '', '', 0, 'GAP', 25),
(534, 'Die DSGVO gilt für alle Unternehmen,die Daten von_____verarbeiten.', '', '', 0, 'GAP', 25),
(535, 'Variable Kosten steigen mit der Produktionsmenge.', NULL, 'Variable Kosten steigen mit der Menge.', 0, 'TF', 26),
(536, 'Der Break-even-Point ist erreicht, wenn Gewinn = 0 ist.', NULL, 'Break-even bedeutet Gewinn = 0.', 0, 'TF', 26),
(537, 'Was gehört NICHT zu den drei Zielen des magischen Dreiecks?', NULL, 'Kundenzufriedenheit gehört nicht zum magischen Dreieck.', 0, 'MC', 26),
(538, 'Welche Kostenart zählt zu den fixen Kosten?', NULL, 'Miete ist eine fixe Kostenart.', 0, 'MC', 26),
(539, 'Was beschreibt eine Make-or-Buy-Entscheidung?', NULL, 'Make-or-Buy entscheidet über Eigenentwicklung oder Einkauf.', 0, 'MC', 26),
(540, 'Der_____zeigt, ab welcher Absatzmenge ein Unternehmen kostendeckend arbeitet.Der **Break-even-Point** zeigt die Kostendeckung.', '', 'Der **Break-even-Point** zeigt die Kostendeckung.', 0, 'GAP', 26),
(541, 'Die Liquidität beschreibt die Fähigkeit,die Fähigkeit,_____zu bezahlen.Liquidität beschreibt die Fähigkeit, **Verbindlichkeiten** zu bezahlen.', '', 'Liquidität beschreibt die Fähigkeit, **Verbindlichkeiten** zu bezahlen.', 0, 'GAP', 26),
(542, 'Eine_____-Analyse vergleicht Aufwand und Nutzen eines Projekts.Eine **Kosten-Nutzen-Analyse** vergleicht Aufwand und Nutzen.', '', 'Eine **Kosten-Nutzen-Analyse** vergleicht Aufwand und Nutzen.', 0, 'GAP', 26),
(543, 'Fixe Kosten bleiben unabhängig von derunabhängig von der_____konstant.Fixe Kosten bleiben unabhängig von der **Menge** konstant.', '', 'Fixe Kosten bleiben unabhängig von der **Menge** konstant.', 0, 'GAP', 26),
(544, 'Ein Budget ist eine_____für zukünftige Ausgaben.Ein Budget ist eine **Planung** für zukünftige Ausgaben.', '', 'Ein Budget ist eine **Planung** für zukünftige Ausgaben.', 0, 'GAP', 26),
(545, 'Ein Use-Case-Diagramm zeigt die Interaktionen zwischen Akteuren und System.', NULL, 'Use-Case-Diagramme zeigen Interaktionen.', 0, 'TF', 27),
(546, 'Eine Aggregation ist stärker als eine Komposition.', NULL, 'Aggregation ist schwächer als Komposition.', 0, 'TF', 27),
(547, 'Welches Diagramm zeigt den Ablauf von Nachrichten zwischen Objekten?', NULL, 'Sequenzdiagramm zeigt Nachrichtenabläufe.', 0, 'MC', 27),
(548, 'Welche Beziehung zeigt eine „ist-ein“-Beziehung?', NULL, 'Vererbung zeigt eine „ist-ein“-Beziehung.', 0, 'MC', 27),
(549, 'Was zeigt ein Klassendiagramm NICHT?', NULL, 'Zeitlicher Ablauf gehört nicht ins Klassendiagramm.', 0, 'MC', 27),
(550, 'Ein_____diagramm beschreibt Abläufe und Entscheidungen.Ein **Aktivitätsdiagramm** beschreibt Abläufe.', '', 'Ein **Aktivitätsdiagramm** beschreibt Abläufe.', 0, 'GAP', 27),
(551, 'In einem Klassendiagramm verbinden_____die Klassen miteinander.In einem Klassendiagramm verbinden **Beziehungen** die Klassen.', '', 'In einem Klassendiagramm verbinden **Beziehungen** die Klassen.', 0, 'GAP', 27),
(552, 'Eine Komposition bedeutet, dass das Teil ohne das Ganze_____kann.', '', '', 0, 'GAP', 27),
(553, 'Ein Akteur repräsentiert eine_____die mit dem System interagiert.', '', '', 0, 'GAP', 27),
(554, 'Sequenzdiagramme zeigen den_____von Nachrichten.', '', '', 0, 'GAP', 27),
(555, 'Overfitting bedeutet, dass ein Modell zu stark an die Trainingsdaten angepasst ist.', NULL, 'Overfitting = zu starke Anpassung an Trainingsdaten.', 0, 'TF', 28),
(556, 'Unüberwachtes Lernen benötigt gelabelte Daten.', NULL, 'Unüberwachtes Lernen benötigt **keine** gelabelten Daten.', 0, 'TF', 28),
(557, 'Was ist ein Beispiel für überwachtes Lernen?', NULL, 'Klassifikation ist überwachtes Lernen.', 0, 'MC', 28),
(558, 'Was ist ein Neuron im neuronalen Netz?', NULL, 'Ein Neuron ist eine mathematische Funktion.', 0, 'MC', 28),
(559, 'Welche Metrik misst die Genauigkeit eines Klassifikationsmodells?', NULL, 'Accuracy misst die Genauigkeit.', 0, 'MC', 28),
(560, 'Eine While-Schleife wird ausgeführt, solange die Bedingung wahr ist.', NULL, 'While-Schleife läuft, solange die Bedingung wahr ist.', 0, 'TF', 29),
(561, 'Call-by-Reference übergibt eine Kopie des Werts.', NULL, 'Call-by-Reference übergibt **keine Kopie**, sondern eine Referenz.', 0, 'TF', 29),
(562, 'Welche Struktur beschreibt eine Verzweigung?', NULL, 'if beschreibt eine Verzweigung.', 0, 'MC', 29),
(563, 'Welche Suche prüft jedes Element nacheinander?', NULL, 'Lineare Suche prüft jedes Element.', 0, 'MC', 29),
(564, 'Was ist ein Algorithmus?', NULL, 'Ein Algorithmus ist eine eindeutige Schrittfolge.', 0, 'MC', 29),
(565, 'Was beschreibt Pseudocode am besten?', NULL, NULL, 0, 'MC', 23),
(566, 'Welche Struktur wird typischerweise für Wiederholungen im Pseudocode genutzt?', NULL, NULL, 0, 'MC', 23),
(567, 'Welche Kontrollstruktur dient zur Entscheidung?', NULL, NULL, 0, 'MC', 23),
(568, 'Was ist ein Objekt in der OOP?', NULL, NULL, 0, 'MC', 23),
(569, 'Welche Schleife eignet sich, wenn die Anzahl der Wiederholungen bekannt ist?', NULL, NULL, 0, 'MC', 23),
(570, 'Welche typische Schreibweise beschreibt eine Methode im Pseudocode?', NULL, NULL, 0, 'MC', 23),
(571, 'Welche Datenstruktur speichert Elemente in Reihenfolge?', NULL, NULL, 0, 'MC', 23),
(572, 'Welche Schleife wird mindestens einmal ausgeführt?', NULL, NULL, 0, 'MC', 23),
(573, 'Welche Aussage beschreibt Vererbung?', NULL, NULL, 0, 'MC', 23),
(574, 'Was beschreibt Polymorphie?', NULL, NULL, 0, 'MC', 23),
(575, 'Welche Elemente gehören zu einer Klasse?', NULL, NULL, 1, 'MC', 23),
(576, 'Welche Schritte gehören typischerweise zu einem Algorithmus?', NULL, NULL, 1, 'MC', 23),
(577, 'Welche Eigenschaften hat guter Pseudocode?', NULL, NULL, 1, 'MC', 23),
(578, 'Welche OOP‑Konzepte gehören zu den „vier Grundpfeilern“?', NULL, NULL, 1, 'MC', 23),
(579, 'Welche Strukturen sind Kontrollstrukturen?', NULL, NULL, 1, 'MC', 23),
(580, 'Pseudocode muss sich an die Syntax einer Programmiersprache halten.', NULL, NULL, 0, 'TF', 23),
(581, 'Ein Algorithmus muss endlich sein.', NULL, NULL, 0, 'TF', 23),
(582, 'Ein Konstruktor initialisiert ein Objekt.', NULL, NULL, 0, 'TF', 23),
(583, 'Ein Algorithmus muss immer deterministisch sein.', NULL, NULL, 0, 'TF', 23),
(584, 'Eine Klasse kann Methoden und Attribute enthalten.', NULL, NULL, 0, 'TF', 23),
(585, 'Polymorphie bedeutet, dass eine Klasse keine Attribute besitzt.', NULL, NULL, 0, 'TF', 23),
(586, 'WHILE-Schleifen werden immer mindestens einmal ausgeführt.', NULL, NULL, 0, 'TF', 23),
(587, 'Objekte entstehen aus Klassen.', NULL, NULL, 0, 'TF', 23),
(588, 'Pseudocode ist immer ausführbar', NULL, NULL, 0, 'TF', 23),
(589, 'Eine Liste kann mehrere Elemente enthalten.', NULL, NULL, 0, 'TF', 23),
(590, 'Was ist ein Attribut?', NULL, NULL, 0, 'MC', 23),
(591, 'Was ist ein Parameter?', NULL, NULL, 0, 'MC', 23),
(592, 'Was beschreibt Kapselung?', NULL, NULL, 0, 'MC', 23),
(593, 'Was ist ein Rückgabewert?', NULL, NULL, 0, 'MC', 23),
(594, 'Was ist ein Algorithmus?', NULL, NULL, 0, 'MC', 23),
(595, 'Wofür wird Pseudocode hauptsächlich verwendet?', NULL, NULL, 0, 'MC', 23),
(596, 'Welche Schreibweise ist typisch für eine Zuweisung im Pseudocode?', NULL, NULL, 0, 'MC', 23),
(597, 'Welche Struktur beschreibt eine Wiederholung bis eine Bedingung erfüllt ist?', NULL, NULL, 0, 'MC', 23),
(598, 'Was ist ein Vorteil von Pseudocode?', NULL, NULL, 0, 'MC', 23),
(599, 'Welche Struktur wird genutzt, um eine Liste zu durchlaufen?', NULL, NULL, 0, 'MC', 23),
(600, 'Was bedeutet „INITIALISIERE x MIT 0“?', NULL, NULL, 0, 'MC', 23),
(601, 'Welche Schreibweise beschreibt eine Bedingung?', NULL, NULL, 0, 'MC', 23),
(602, 'Was bedeutet „GIB x AUS“ im Pseudocode?', NULL, NULL, 0, 'MC', 23),
(603, 'Welche Struktur beendet eine Schleife sofort?', NULL, NULL, 0, 'MC', 23),
(604, 'Was ist ein typischer Fehler im Pseudocode?', NULL, NULL, 0, 'MC', 23),
(605, 'Welche Elemente können in Pseudocode vorkommen?', NULL, NULL, 1, 'MC', 23),
(606, 'Welche Vorteile hat Pseudocode?', NULL, NULL, 1, 'MC', 23),
(607, 'Welche typischen Schlüsselwörter findet man in Pseudocode?', NULL, NULL, 1, 'MC', 23),
(608, 'Pseudocode ist eine formale Sprache.', NULL, NULL, 0, 'TF', 23),
(609, 'Pseudocode kann zur Kommunikation zwischen Entwicklern genutzt werden.', NULL, NULL, 0, 'TF', 23),
(610, 'Pseudocode ist immer identisch mit der späteren Programmiersprache.', NULL, NULL, 0, 'TF', 23),
(611, 'Pseudocode kann Kommentare enthalten.', NULL, NULL, 0, 'TF', 23),
(612, 'Pseudocode kann zur Planung von Algorithmen verwendet werden.', NULL, NULL, 0, 'TF', 23),
(613, 'Welche Aussagen über Pseudocode sind korrekt?', NULL, NULL, 1, 'MC', 23),
(614, 'Welche Aussagen über Algorithmen sind korrekt?', NULL, NULL, 1, 'MC', 23);



        ");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("DELETE FROM `questions` WHERE `Id` BETWEEN 1 AND 2;");
        }
    }
}
