// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Schulprojekt.Data;

#nullable disable

namespace Schulprojekt.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260304193702_Added_Relation_Thema_Questionset")]
    partial class Added_Relation_Thema_Questionset
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Schulprojekt.Data.GapField", b =>
                {
                    b.Property<int>("GapId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GapId"));

                    b.Property<bool>("CaseSensitive")
                        .HasColumnType("bit");

                    b.Property<string>("CorrectText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GapIndex")
                        .HasColumnType("int");

                    b.Property<string>("InputType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.HasKey("GapId");

                    b.HasIndex("QuestionId", "GapIndex")
                        .IsUnique();

                    b.ToTable("GapFields");
                });

            modelBuilder.Entity("Schulprojekt.Data.GapOption", b =>
                {
                    b.Property<int>("GapOptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GapOptionId"));

                    b.Property<int>("GapId")
                        .HasColumnType("int");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int>("OptionOrder")
                        .HasColumnType("int");

                    b.Property<string>("OptionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GapOptionId");

                    b.HasIndex("GapId", "OptionOrder")
                        .IsUnique();

                    b.ToTable("GapOptions");
                });

            modelBuilder.Entity("Schulprojekt.Data.McAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<int>("OptionOrder")
                        .HasColumnType("int");

                    b.Property<string>("OptionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("McAnswers");
                });

            modelBuilder.Entity("Schulprojekt.Data.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllowsMultiple")
                        .HasColumnType("bit");

                    b.Property<string>("EndText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuestionSetId")
                        .HasColumnType("int");

                    b.Property<string>("QuestionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StartText")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionSetId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("Schulprojekt.Data.QuestionSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<int?>("ThemaId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.HasIndex("ThemaId");

                    b.ToTable("QuestionSets");
                });

            modelBuilder.Entity("Schulprojekt.Data.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("Schulprojekt.Data.Thema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Themen");
                });

            modelBuilder.Entity("Schulprojekt.Data.GapField", b =>
                {
                    b.HasOne("Schulprojekt.Data.Question", "Question")
                        .WithMany("GapFields")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Schulprojekt.Data.GapOption", b =>
                {
                    b.HasOne("Schulprojekt.Data.GapField", "GapField")
                        .WithMany("GapOptions")
                        .HasForeignKey("GapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GapField");
                });

            modelBuilder.Entity("Schulprojekt.Data.McAnswer", b =>
                {
                    b.HasOne("Schulprojekt.Data.Question", "Question")
                        .WithMany("McAnswers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Schulprojekt.Data.Question", b =>
                {
                    b.HasOne("Schulprojekt.Data.QuestionSet", "QuestionSet")
                        .WithMany("Questions")
                        .HasForeignKey("QuestionSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuestionSet");
                });

            modelBuilder.Entity("Schulprojekt.Data.QuestionSet", b =>
                {
                    b.HasOne("Schulprojekt.Data.Team", "Team")
                        .WithMany("QuestionSets")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Schulprojekt.Data.Thema", "Thema")
                        .WithMany("QuestionSets")
                        .HasForeignKey("ThemaId");

                    b.Navigation("Team");

                    b.Navigation("Thema");
                });

            modelBuilder.Entity("Schulprojekt.Data.GapField", b =>
                {
                    b.Navigation("GapOptions");
                });

            modelBuilder.Entity("Schulprojekt.Data.Question", b =>
                {
                    b.Navigation("GapFields");

                    b.Navigation("McAnswers");
                });

            modelBuilder.Entity("Schulprojekt.Data.QuestionSet", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("Schulprojekt.Data.Team", b =>
                {
                    b.Navigation("QuestionSets");
                });

            modelBuilder.Entity("Schulprojekt.Data.Thema", b =>
                {
                    b.Navigation("QuestionSets");
                });
#pragma warning restore 612, 618
        }
    }
}
